# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 22:09
from __future__ import unicode_literals

from django.db import migrations, models
import webresources.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', webresources.models.NormalizedURLField(max_length=1000, unique=True)),
            ],
        ),
    ]
