# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 19:29
from __future__ import unicode_literals

from django.db import migrations
import webresources.models


class Migration(migrations.Migration):

    dependencies = [
        ('webresources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='location',
            field=webresources.models.NocryptoURLField(max_length=1000, unique=True),
        ),
    ]
