# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 15:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webresources', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='nominated_projects',
            new_name='projects',
        ),
    ]
