# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 20:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webresources', '0002_auto_20171014_0828'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Resource',
            new_name='OldResource',
        ),
    ]
