# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 21:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webresources', '0003_auto_20171019_1320'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OldResource',
            new_name='Resource',
        ),
    ]
