# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 20:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webresources', '0005_auto_20171019_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='projects',
        ),
    ]
