# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 22:09
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIEndpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.URLField(unique=True)),
                ('importer_class_name', models.TextField(choices=[('AITCollectionsImporter', 'AITCollectionsImporter'), ('AITPartnerImporter', 'AITPartnerImporter')], default='OAIPMHImporter')),
                ('last_updated', models.DateTimeField(editable=False, null=True)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('raw_metadata', models.TextField(blank=True, null=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Organization')),
            ],
            options={
                'verbose_name': 'API Endpoint',
            },
        ),
    ]
