# Generated by Django 2.0.1 on 2018-01-23 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datasources', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiendpoint',
            name='raw_metadata',
        ),
    ]
