# Generated by Django 2.0.5 on 2018-06-02 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datasources', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiendpoint',
            name='organization',
        ),
        migrations.DeleteModel(
            name='APIEndpoint',
        ),
    ]
