# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 20:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datasources', '0002_remove_apiendpoint_agent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apiendpoint',
            options={'verbose_name': 'API Endpoint'},
        ),
    ]
