# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 22:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datasources', '0002_auto_20170927_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiendpoint',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Organization'),
        ),
    ]
