# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 22:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datasources', '0002_apiendpoint_last_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apiendpoint',
            old_name='metadata',
            new_name='metadatums',
        ),
    ]
