# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 22:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datasources', '0003_auto_20170927_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiendpoint',
            name='protocol',
        ),
        migrations.DeleteModel(
            name='APIProtocol',
        ),
    ]
