# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasources', '0004_auto_20170927_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiendpoint',
            name='importer_class_name',
            field=models.CharField(default='OAIPMHImporter', max_length=50),
        ),
    ]
