# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasources', '0006_remove_apiendpoint_metadatums'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiendpoint',
            name='raw_metadata',
            field=models.TextField(blank=True, null=True),
        ),
    ]
