# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 22:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('archives', '0001_initial'),
        ('webresources', '0001_initial'),
        ('metadata', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='collections', to='core.Organization'),
        ),
        migrations.AddField(
            model_name='claim',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archives.Collection'),
        ),
        migrations.AddField(
            model_name='claim',
            name='keywords',
            field=models.ManyToManyField(blank=True, to='metadata.Keyword'),
        ),
        migrations.AddField(
            model_name='claim',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='webresources.Resource'),
        ),
    ]
