# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-10 21:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0002_auto_20171213_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='resource',
        ),
        migrations.DeleteModel(
            name='Claim',
        ),
    ]
