# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 22:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0002_auto_20171005_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='webresources.Resource'),
        ),
        migrations.AlterField(
            model_name='holding',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holdings', to='webresources.Resource'),
        ),
    ]
