# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 23:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0002_auto_20170927_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='metadata',
            field=models.ManyToManyField(blank=True, null=True, to='metadata.Metadatum'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='metadata',
            field=models.ManyToManyField(blank=True, null=True, to='metadata.Metadatum'),
        ),
        migrations.AlterField(
            model_name='holding',
            name='metadata',
            field=models.ManyToManyField(blank=True, null=True, to='metadata.Metadatum'),
        ),
    ]
