# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 22:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0002_auto_20170930_1800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claim',
            old_name='metadata',
            new_name='metadatums',
        ),
        migrations.RenameField(
            model_name='collection',
            old_name='metadata',
            new_name='metadatums',
        ),
        migrations.RenameField(
            model_name='holding',
            old_name='metadata',
            new_name='metadatums',
        ),
    ]
