# Generated by Django 2.0.5 on 2018-06-02 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0002_auto_20180421_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='administrators',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='holding',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='holding',
            name='resource',
        ),
        migrations.DeleteModel(
            name='Collection',
        ),
        migrations.DeleteModel(
            name='Holding',
        ),
    ]
