# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-15 19:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('archives', '0003_auto_20180110_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='administrators',
            field=models.ManyToManyField(related_name='collections_administered', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collection',
            name='invited_administrators',
            field=models.ManyToManyField(related_name='collections_administered_invited', to=settings.AUTH_USER_MODEL),
        ),
    ]
