# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0004_auto_20170927_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='name',
            field=models.TextField(verbose_name='Name'),
        ),
    ]
