# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0001_initial'),
        ('archives', '0004_auto_20171023_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='created',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='deprecated',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='created',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='deprecated',
        ),
        migrations.RemoveField(
            model_name='holding',
            name='created',
        ),
        migrations.RemoveField(
            model_name='holding',
            name='deprecated',
        ),
        migrations.AddField(
            model_name='claim',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='claim',
            name='keywords',
            field=models.ManyToManyField(blank=True, to='metadata.Keyword'),
        ),
        migrations.AddField(
            model_name='claim',
            name='raw_metadata',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='holding',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='holding',
            name='keywords',
            field=models.ManyToManyField(blank=True, to='metadata.Keyword'),
        ),
    ]
