# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 20:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0005_auto_20171023_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='title',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='title',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='holding',
            name='title',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='collections', to='core.Organization'),
        ),
        migrations.AlterField(
            model_name='holding',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='archives.Collection'),
        ),
    ]
