# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 13:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0005_auto_20171004_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='metadatums',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='metadatums',
        ),
        migrations.RemoveField(
            model_name='holding',
            name='metadatums',
        ),
    ]
