# Generated by Django 2.0.1 on 2018-01-29 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0005_auto_20180123_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
