# Generated by Django 2.0.1 on 2018-01-29 23:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0006_auto_20180129_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='invited_administrators',
        ),
        migrations.AlterField(
            model_name='collection',
            name='administrators',
            field=models.ManyToManyField(blank=True, related_name='collections_administered', to=settings.AUTH_USER_MODEL),
        ),
    ]
