# Generated by Django 2.0.1 on 2018-02-06 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0007_auto_20180129_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holding',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
