# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 22:09
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('webresources', '0001_initial'),
        ('metadata', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Nomination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('raw_metadata', models.TextField(blank=True, null=True)),
                ('keywords', models.ManyToManyField(blank=True, to='metadata.Keyword')),
                ('nominated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('raw_metadata', models.TextField(blank=True, null=True)),
                ('nomination_policy', models.CharField(choices=[('Anonymous', "Anonymous: anyone can nominate, even if they're not logged in."), ('Open', 'Open: anyone with a Cobweb account can nominate.'), ('Restricted', 'Restricted: only selected users can nominate.')], default='Open', max_length=10)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Deleted', 'Deleted')], default='Active', max_length=8)),
                ('administered_by', models.ManyToManyField(related_name='projects_administered', to=settings.AUTH_USER_MODEL, verbose_name='administrators')),
                ('keywords', models.ManyToManyField(blank=True, to='metadata.Keyword')),
                ('nominator_blacklist', models.ManyToManyField(blank=True, related_name='projects_blacklisted', to=settings.AUTH_USER_MODEL)),
                ('nominators', models.ManyToManyField(blank=True, related_name='projects_nominating', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='nomination',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nominations', to='projects.Project'),
        ),
        migrations.AddField(
            model_name='nomination',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nominations', to='webresources.Resource'),
        ),
        migrations.AlterUniqueTogether(
            name='nomination',
            unique_together=set([('resource', 'project', 'nominated_by')]),
        ),
    ]
