# Generated by Django 2.0.5 on 2018-06-04 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('webarchives', '0001_initial'),
        ('projects', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='imported_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='webarchives.ImportedRecord'),
        ),
        migrations.AddField(
            model_name='claim',
            name='nomination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='projects.Nomination'),
        ),
        migrations.AddField(
            model_name='claim',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='core.Organization'),
        ),
        migrations.AlterUniqueTogether(
            name='nomination',
            unique_together={('resource', 'project')},
        ),
        migrations.AlterUniqueTogether(
            name='claim',
            unique_together={('nomination', 'organization')},
        ),
    ]
