# Generated by Django 2.0.4 on 2018-04-24 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nomination',
            name='status',
        ),
        migrations.RemoveField(
            model_name='nomination',
            name='subject_headings',
        ),
        migrations.RemoveField(
            model_name='nomination',
            name='tags',
        ),
        migrations.AddField(
            model_name='nomination',
            name='is_claimed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nomination',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nomination',
            name='suggested_crawl_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nomination',
            name='suggested_crawl_frequency',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
