# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-10 20:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='administered_by',
            new_name='administrators',
        ),
    ]
