# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 01:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('webresources', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomination',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webresources.Resource'),
        ),
        migrations.AlterUniqueTogether(
            name='nomination',
            unique_together=set([('resource', 'project', 'nominated_by')]),
        ),
    ]
