# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-10 21:52
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0003_auto_20180110_1352'),
        ('webresources', '0001_initial'),
        ('metadata', '0001_initial'),
        ('projects', '0002_auto_20180110_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('raw_metadata', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(verbose_name='Starting Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Ending Date')),
                ('max_links', models.IntegerField(blank=True, null=True, verbose_name='Maximum Links')),
                ('time_limit', models.DurationField(blank=True, null=True, verbose_name='Time Limit')),
                ('document_limit', models.IntegerField(blank=True, null=True, verbose_name='Document Limit')),
                ('data_limit', models.IntegerField(blank=True, null=True, verbose_name='Data Limit (GB)')),
                ('robot_exclusion_override', models.BooleanField(default=False, verbose_name='Override Robot Exclusion?')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archives.Collection')),
                ('keywords', models.ManyToManyField(blank=True, to='metadata.Keyword')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='webresources.Resource')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
