# Generated by Django 2.0.4 on 2018-04-24 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20180424_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomination',
            name='rationale',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nomination',
            name='suggested_crawl_frequency',
            field=models.CharField(blank=True, choices=[('Hourly', 'Hourly'), ('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly')], max_length=50, null=True),
        ),
    ]
