# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0003_auto_20170929_1702'),
        ('projects', '0002_auto_20170927_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='metadata',
            field=models.ManyToManyField(to='metadata.Metadatum'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.TextField(verbose_name='Name'),
        ),
    ]
