# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 23:56
from __future__ import unicode_literals

from django.db import migrations, models

def project_admins(apps, schema_editor):
    for project in apps.get_model("projects", "Project").objects.all():
        if project.established_by:
            project.administered_by.add(project.established_by)

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_affiliations'),
        ('projects', '0002_auto_20170922_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='administered_by',
            field=models.ManyToManyField(related_name='projects_administered', to='core.Agent'),
        ),
        migrations.RunPython(project_admins),
    ]
