# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-06 15:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20171005_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='administered_by',
            field=models.ManyToManyField(related_name='projects_administered', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Name'),
        ),
    ]
