# Generated by Django 2.0.5 on 2018-07-17 23:44

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [('projects', '0004_auto_20180717_1641'), ('projects', '0005_auto_20180717_1642'), ('projects', '0006_auto_20180717_1643'), ('projects', '0007_auto_20180717_1643'), ('projects', '0008_auto_20180717_1643')]

    dependencies = [
        ('projects', '0003_auto_20180717_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nomination',
            old_name='suggested_crawl_frequency',
            new_name='crawl_frequency',
        ),
        migrations.RenameField(
            model_name='nomination',
            old_name='suggested_crawl_start_date',
            new_name='crawl_start_date',
        ),
        migrations.RenameField(
            model_name='nomination',
            old_name='suggested_crawl_end_date',
            new_name='crawl_end_date',
        ),
        migrations.RenameField(
            model_name='nomination',
            old_name='suggested_follow_links',
            new_name='follow_links',
        ),
        migrations.RenameField(
            model_name='nomination',
            old_name='suggested_page_scope',
            new_name='page_scope',
        ),
    ]
