# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-06 16:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0003_auto_20171006_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='nominators',
            field=models.ManyToManyField(related_name='projects_nominating', to=settings.AUTH_USER_MODEL),
        ),
    ]
