# Generated by Django 2.0.4 on 2018-04-24 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_crawlscope'),
        ('projects', '0003_auto_20180424_1340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nomination',
            old_name='is_deleted',
            new_name='deleted',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='status',
        ),
        migrations.RemoveField(
            model_name='nomination',
            name='is_claimed',
        ),
        migrations.AddField(
            model_name='claim',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='crawl_scope',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.CrawlScope'),
        ),
        migrations.AddField(
            model_name='claim',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nomination',
            name='needs_claim',
            field=models.BooleanField(default=True),
        ),
    ]
