# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-10 22:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webresources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0003_claim'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nomination',
            old_name='nominated_by',
            new_name='nominated_by_fk',
        ),
        migrations.AlterUniqueTogether(
            name='nomination',
            unique_together=set([('resource', 'project', 'nominated_by_fk')]),
        ),
    ]
