# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-06 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_nominators'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='nomination_policy',
            field=models.CharField(choices=[('A', 'Anonymous'), ('O', 'Open'), ('R', 'Restricted')], default='o', max_length=1),
        ),
    ]
