# Generated by Django 2.0.5 on 2018-05-09 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0002_auto_20180421_1554'),
        ('projects', '0004_auto_20180424_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='has_holding',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='claim',
            name='imported_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='archives.Holding'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='nomination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='projects.Nomination'),
        ),
        migrations.AlterField(
            model_name='nomination',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominations', to='projects.Project'),
        ),
    ]
