# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 00:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


def project_admins(apps, schema_editor):
    for project in apps.get_model("projects", "Project").objects.all():
        for agent in project.administered_by.all():
            project.administered_by_user.add(agent.user)

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0004_remove_project_established_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='administered_by_user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(project_admins),
    ]
