# Generated by Django 2.0.5 on 2018-07-18 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20180717_1641_squashed_0008_auto_20180717_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='crawl_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='crawl_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nomination',
            name='crawl_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nomination',
            name='crawl_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
