# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-10 22:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20180110_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomination',
            name='nominated_by_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nominated_by_fk_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
