# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 15:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_nomination_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='keywords',
            field=models.ManyToManyField(blank=True, to='metadata.Keyword'),
        ),
        migrations.AlterField(
            model_name='project',
            name='nominators',
            field=models.ManyToManyField(blank=True, related_name='projects_nominating', to=settings.AUTH_USER_MODEL),
        ),
    ]
