# Generated by Django 2.0.7 on 2018-07-24 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20180717_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='any_user_can_nominate',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='page_scope',
            field=models.CharField(blank=True, choices=[('Page', 'Page'), ('Site', 'Site'), ('Domain', 'Domain')], default='Site', max_length=50, null=True),
        ),
    ]
