# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 00:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_administered_by_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='administered_by',
        ),
    ]
