# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20171004_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='metadatums',
        ),
        migrations.AddField(
            model_name='project',
            name='raw_metadata',
            field=models.TextField(blank=True, null=True),
        ),
    ]
