# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 22:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20171014_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomination',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nominations', to='webresources.Resource'),
        ),
    ]
