# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-10 22:17
from __future__ import unicode_literals

from django.db import migrations
from django.db.models import Q


def migrate_data(apps, schema_editor):
    Nomination = apps.get_model('projects', 'Nomination')
    for nom in Nomination.objects.all():
        nom.nominated_by.add(nom.nominated_by_fk.id)
        similar = (
            Nomination.objects
            .filter(resource=nom.resource, project=nom.project)
            .exclude(id=nom.id)
        )
        for nom2 in similar:
            nom.nominated_by.add(nom2.nominated_by_fk.id)
            nom.keywords.add(*nom2.keywords.all())
            print(f'Deleted Nomination {nom2.id}: duplicates {nom.id}')
            print(f'Project: {nom.project}, Resource: {nom.resource}')
            nom.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_nomination_nominated_by'),
    ]

    operations = [
        migrations.RunPython(migrate_data),
    ]
