# Generated by Django 2.0.8 on 2018-08-23 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20180724_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='any_user_can_nominate',
        ),
    ]
