# Generated by Django 2.0.5 on 2018-05-29 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20180522_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nomination',
            name='needs_claim',
        ),
    ]
