# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 00:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0001_initial'),
        ('projects', '0007_auto_20170925_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='keywords',
            field=models.ManyToManyField(to='metadata.Keyword'),
        ),
    ]
