# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 17:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0007_auto_20171017_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='nominator_blacklist',
            field=models.ManyToManyField(blank=True, related_name='projects_blacklisted', to=settings.AUTH_USER_MODEL),
        ),
    ]
