# Generated by Django 2.0.5 on 2018-05-31 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20180510_1051'),
        ('languages_plus', '0004_auto_20171214_0004'),
        ('projects', '0007_remove_nomination_needs_claim'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomination',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nomination',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='languages_plus.Language'),
        ),
        migrations.AddField(
            model_name='nomination',
            name='subject_headings',
            field=models.ManyToManyField(blank=True, to='core.SubjectHeading'),
        ),
        migrations.AddField(
            model_name='nomination',
            name='tags',
            field=models.ManyToManyField(blank=True, to='core.Tag'),
        ),
        migrations.AddField(
            model_name='nomination',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
