# Generated by Django 2.0.5 on 2018-06-01 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20180531_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
