# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_project_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='sector',
            field=models.CharField(choices=[('a', 'Active'), ('i', 'Inactive'), ('d', 'Deleted')], default='a', max_length=1, verbose_name='Sector'),
        ),
    ]
