# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 20:15
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0001_initial'),
        ('projects', '0008_project_nominator_blacklist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nomination',
            name='created',
        ),
        migrations.RemoveField(
            model_name='nomination',
            name='deprecated',
        ),
        migrations.AddField(
            model_name='nomination',
            name='keywords',
            field=models.ManyToManyField(blank=True, to='metadata.Keyword'),
        ),
        migrations.AddField(
            model_name='nomination',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nomination',
            name='raw_metadata',
            field=models.TextField(blank=True, null=True),
        ),
    ]
