# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-11 00:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webresources', '0001_initial'),
        ('projects', '0008_auto_20180110_1617'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='nomination',
            unique_together=set([('resource', 'project')]),
        ),
    ]
