# Generated by Django 2.0.5 on 2018-06-01 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20180601_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='imported_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='webarchives.ImportedRecord'),
        ),
    ]
