# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 13:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_project_sector'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='sector',
            new_name='status',
        ),
    ]
