# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 20:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20171023_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomination',
            name='title',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='nomination',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominations', to='projects.Project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='administered_by',
            field=models.ManyToManyField(related_name='projects_administered', to=settings.AUTH_USER_MODEL, verbose_name='administrators'),
        ),
        migrations.AlterField(
            model_name='project',
            name='nomination_policy',
            field=models.CharField(choices=[('A', "Anonymous: anyone can nominate, even if they're not logged in."), ('O', 'Open: anyone with a Cobweb account can nominate.'), ('R', 'Restricted: only selected users can nominate.')], default='O', max_length=1),
        ),
    ]
