# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-11 19:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_remove_nomination_nominated_by_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='resource',
        ),
        migrations.AddField(
            model_name='claim',
            name='nomination',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='projects.Nomination'),
            preserve_default=False,
        ),
    ]
