# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20170926_0616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='created',
        ),
        migrations.RemoveField(
            model_name='project',
            name='deprecated',
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('a', 'Active'), ('i', 'Inactive'), ('d', 'Deleted')], default='a', max_length=1),
        ),
    ]
