# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 15:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_remove_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomination',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nominations', to='projects.Project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='nomination_policy',
            field=models.CharField(choices=[('Anonymous', "Anonymous: anyone can nominate, even if they're not logged in."), ('Open', 'Open: anyone with a Cobweb account can nominate.'), ('Restricted', 'Restricted: only selected users can nominate.')], default='Open', max_length=10),
        ),
    ]
