# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-11 19:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0003_auto_20180110_1352'),
        ('projects', '0011_auto_20180111_1115'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='claim',
            unique_together=set([('nomination', 'collection')]),
        ),
    ]
