# Generated by Django 2.1.1 on 2018-10-03 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20180928_1104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nomination',
            old_name='author',
            new_name='creator',
        ),
        migrations.AlterField(
            model_name='claim',
            name='has_holding',
            field=models.BooleanField(default=False, help_text='\n    Check here to indicate that your organization has both made this claim to\n    capture the nominated URL and that you have successfully captured it.\n    ', verbose_name='held'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='rights_considerations',
            field=models.TextField(blank=True, null=True, verbose_name='access considerations'),
        ),
        migrations.AlterField(
            model_name='nomination',
            name='rationale',
            field=models.TextField(blank=True, help_text='\n    Describe why you think this particular resource should be included with\n    this project.\n    ', null=True),
        ),
        migrations.AlterField(
            model_name='nomination',
            name='rights_considerations',
            field=models.TextField(blank=True, null=True, verbose_name='access considerations'),
        ),
        migrations.AlterField(
            model_name='nomination',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='\n    Enter or choose brief descriptive terms. Descriptive terms can include more\n    than one word, separated by spaces and ending with a hard return for entry.\n    ', to='core.Tag'),
        ),
    ]
