# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 15:38
from __future__ import unicode_literals

from django.db import migrations


def expand_nomination_policy_field(apps, schema_editor):
    np_map = {
        'A': 'Anonymous',
        'O': 'Open',
        'R': 'Restricted',
    }
    for project in apps.get_model('projects', 'Project').objects.all():
        if project.nomination_policy not in np_map.values():
            project.nomination_policy = np_map[
                project.nomination_policy
            ]
            project.save()


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20171212_0736'),
    ]

    operations = [
        migrations.RunPython(expand_nomination_policy_field),
    ]
