# Generated by Django 2.0.1 on 2018-01-23 19:02

from django.db import migrations
import metadata.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20180111_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='raw_metadata',
        ),
        migrations.RemoveField(
            model_name='nomination',
            name='raw_metadata',
        ),
        migrations.RemoveField(
            model_name='project',
            name='raw_metadata',
        ),
        migrations.AlterField(
            model_name='claim',
            name='metadata',
            field=metadata.models.MetadataJSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nomination',
            name='metadata',
            field=metadata.models.MetadataJSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='metadata',
            field=metadata.models.MetadataJSONField(blank=True, null=True),
        ),
    ]
