# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_auto_20171212_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Deleted', 'Deleted'), ('Inactive', 'Inactive')], default='a', max_length=8),
        ),
    ]
