# Generated by Django 2.0.1 on 2018-01-23 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_auto_20180123_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='data_limit',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='document_limit',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='max_links',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='robot_exclusion_override',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='time_limit',
        ),
    ]
