# Generated by Django 2.1.1 on 2018-10-03 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_auto_20181002_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='intended_crawling_tool',
            field=models.CharField(blank=True, choices=[('Archive-It', 'Archive-It'), ('Brozzler', 'Brozzler'), ('Heritrix 1', 'Heritrix 1'), ('Heritrix 3', 'Heritrix 3'), ('Webrecorder', 'Webrecorder'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='nomination',
            name='intended_crawling_tool',
            field=models.CharField(blank=True, choices=[('Archive-It', 'Archive-It'), ('Brozzler', 'Brozzler'), ('Heritrix 1', 'Heritrix 1'), ('Heritrix 3', 'Heritrix 3'), ('Webrecorder', 'Webrecorder'), ('Other', 'Other')], max_length=50, null=True),
        ),
    ]
