# Generated by Django 2.0.1 on 2018-01-29 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_auto_20180123_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='archives.Collection'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
