# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 17:28
from __future__ import unicode_literals

from django.db import migrations


def expand_fields(apps, schema_editor):
    model = apps.get_model('core', 'Organization')
    for old_value, new_value in {'a': 'Academic',
                                 'c': 'Corporate',
                                 'g': 'Government',
                                 'n': 'Non-Profit',
                                 'o': 'Other'}.items():
        model.objects.filter(sector=old_value).update(sector=new_value)


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_auto_20171212_0927'),
    ]

    operations = [
        migrations.RunPython(expand_fields),
    ]
