# Generated by Django 2.0.1 on 2018-01-29 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_auto_20180129_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='archives.Collection'),
        ),
    ]
