# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_auto_20171212_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Inactive', 'Inactive'), ('Active', 'Active'), ('Deleted', 'Deleted')], default='Active', max_length=8),
        ),
    ]
