# Generated by Django 2.1.1 on 2018-10-12 19:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_auto_20181012_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='collecting_scope',
            field=models.TextField(blank=True, help_text='\n    As applicable, describe the scope and approach that this project is\n    intended to take (such as collecting for defined time frame).\n    ', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='nominator_blacklist',
            field=models.ManyToManyField(blank=True, help_text='\n    Enter names of Cobweb users who cannot nominate to this project. Names can\n    include more than one word, separated by spaces and ending with a hard\n    return for entry.\n    ', related_name='projects_blacklisted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='nominators',
            field=models.ManyToManyField(blank=True, help_text='\n    Enter names of selected Cobweb users who can nominate to projects with a\n    restricted nomination policy. Names can include more than one word,\n    separated by spaces and ending with a hard return for entry.\n    ', related_name='projects_nominating', to=settings.AUTH_USER_MODEL),
        ),
    ]
