# Generated by Django 2.0.1 on 2018-02-06 23:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_auto_20180206_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomination',
            name='nominated_by',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
