# Generated by Django 2.1.2 on 2018-10-26 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_auto_20181026_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(help_text="Choose a URL for your project's profile on Cobweb.", null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='nomination_policy',
            field=models.CharField(choices=[('Public', "Public: anyone can nominate, even if they're not logged in."), ('Cobweb users', 'Cobweb users: anyone with a Cobweb account can nominate.'), ('Restricted', 'Restricted: only selected users can nominate.')], default='Public', max_length=12),
        ),
    ]
