# Generated by Django 2.1.2 on 2018-10-27 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_auto_20181026_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(help_text="Choose a URL for your project's profile on Cobweb.", unique=True),
        ),
    ]
