FROM python:3.5
ENV PYTHONUNBUFFERED 1
RUN apt-get purge -y git 		# to prevent accidentally using git w/in container
RUN apt-get clean
RUN apt-get update
RUN mkdir /code
WORKDIR /code
ADD requirements.txt /code/
RUN pip install -r requirements.txt
RUN apt-get install -y graphviz
ADD requirements-test.txt /code/
RUN pip install -r requirements-test.txt
ADD . /code/
