version: '3'

services:
  solr:
    image: solr:6
    ports:
      - "8983:8983"
    volumes:
      - solr_data:/opt/solr/server/solr/mycores
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - cobweb
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
        test: ['CMD', 'psql', '-h', 'db', '-U', 'postgres', '-c', '\q']
        interval: 30s
        timeout: 10s
        retries: 5
  web:
    image: python:3.6
    volumes:
      - web_usr_local:/usr/local
      - .:/code
      - solr_data:/solr_data
    ports:
      - "8000:8000"
    depends_on:
      - db
      - solr
    working_dir: /code
    environment:
      DEBUG: 'true'
    command: ['bash', '/code/start-development.sh']
volumes:
  postgres_data:
  solr_data:
  web_usr_local:
