version: '3.6'

services:
  solr:
    image: andrewwallace/cobweb_solr:latest
    # volumes:
    #   - solr_data:/opt/solr/server/solr/mycores
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - cobweb
      - /opt/solr/server/solr/configsets/cobweb
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: 2G
    networks:
      - cobwebnet
  db:
    image: postgres:10
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cobwebnet
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 2G
  web:
    image: andrewwallace/cobweb:latest
    ports:
      - "80:8000"
    depends_on:
      - db
      - solr
    working_dir: /code
    command: ['sh', '/code/scripts/start-production.sh']
    environment:
      DEBUG: 'false'
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: 500MB
    networks:
      - cobwebnet
  worker:
    image: andrewwallace/cobweb:latest
    depends_on:
      - db
      - solr
    working_dir: /code
    environment:
      DEBUG: 'true'
    command: ['sh', '/code/scripts/start-worker.sh']
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: 500MB
      restart_policy:
        condition: none
    networks:
      - cobwebnet
volumes:
  postgres_data:
  # solr_data:
networks:
  cobwebnet:
