version: '3'

services:
  solr:
    image: solr:6
    ports:
      - "8983:8983"
    volumes:
      - solr_data:/opt/solr/server/solr/mycores
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - cobweb
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
  web:
    build: .
    command: ['bash', 'start-development.sh']
    volumes:
      - .:/code
      - solr_data:/code/data/solr
    ports:
      - "8000:8000"
    depends_on:
      - db
      - solr
volumes:
  postgres_data: {}
  solr_data: {}
