version: '3.6'

services:
  solr:
    build:
      context: .
      dockerfile: Dockerfile.solr
    image: andrewwallace/cobweb_solr:latest
    ports:
      - "8983:8983"
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - cobweb
      - /opt/solr/server/solr/configsets/cobweb

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
      
  web:
    build:
      context: .
      target: dev
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - solr
    working_dir: /code
    environment:
      DJANGO_SETTINGS_MODULE: "cobweb.settings.debug"
      DEBUG: "true"
      TEST: "false"
      SHELL: "/bin/bash"
      PYTHONPATH: "/code"
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
  
  node:
    image: node
    volumes:
      - .:/code
      - node_modules:/code/node_modules
    working_dir: /code
    environment:
      NODE_PATH: '/node_modules'
    command: ["npx", "webpack", "--config", "webpack.config.js", "--watch"]
  
  sass:
    build:
      context: .
      target: sass
    volumes:
      - ./assets/scss:/scss
      - node_modules:/scss/node_modules
    working_dir: /scss
    command: sass --watch cobweb.scss:cobweb.css
  
  production:
    build:
      context: .
      target: production
    image: andrewwallace/cobweb:latest
    command: "echo 'Built production web image. Bye!'"


volumes:
  postgres_data:
  # web_usr_local:
  # web_dot_local:
  node_modules: