version: '3'

services:
  solr:
    image: solr:6
    ports:
      - "8983:8983"
    volumes:
      - ./data/solr:/opt/solr/server/solr/mycores
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - cobweb
  db:
    image: postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  web:
    build: .
    command: ['bash', 'start-development.sh']
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - solr
  # test:
  #   build: .
  #   volumes:
  #     - .:/code
  #   command: ['bash', 'start-test.sh']
