version: '3'

services:
  solr:
    image: solr:6
    # ports:
    #   - "8983:8983"
    volumes:
      - solr_data:/opt/solr/server/solr/mycores
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - cobweb
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
  web:
    image: python:3.6
    volumes:
      - web_usr_local:/usr/local
      - .:/code
      - solr_data:/solr_data
    ports:
      - "8000:8000"
    depends_on:
      - db
      - solr
    working_dir: /code
    environment:
      DEBUG: 'true'
    stdin_open: true
    tty: true
    command: ['bash', '/code/start-development.sh']
  chrome:
    ports:
      - "4444:4444"
    image: selenium/standalone-chrome
volumes:
  postgres_data:
  solr_data:
  web_usr_local:
