version: '3'

services:
  solr:
    image: solr:6
    # ports:
    #   - "8983:8983"
    volumes:
      - solr_data:/opt/solr/server/solr/mycores
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - cobweb
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    image: python:3.6
    volumes:
      - .:/code
      - solr_data:/solr_data
      - web_usr_local:/usr/local
      - web_dot_local:/root/.local
    ports:
      - "8000:8000"
    depends_on:
      - db
      - solr
    working_dir: /code
    environment:
      DJANGO_SETTINGS_MODULE: 'cobweb.settings.debug'
      DEBUG: 'true'
      TEST: 'false'
      SHELL: '/bin/bash'
    command: ['pipenv', 'run', '/code/start-development.sh']

  test:
    image: python:3.6
    volumes:
      - web_usr_local:/usr/local
      - .:/code
      - solr_data:/solr_data
      - web_dot_local:/root/.local
    depends_on:
      - db
      - solr
    working_dir: /code
    environment:
      DJANGO_SETTINGS_MODULE: 'cobweb.settings.test'
      TEST: 'true'
      DEBUG: 'false'
      SHELL: '/bin/bash'
    stdin_open: true
    tty: true
    command: ['pipenv', 'run', '/code/start-test.sh']

  firefox:
    ports:
      - "4444:4444"
    image: selenium/standalone-firefox
    depends_on: [test]


volumes:
  postgres_data:
  solr_data:
  web_usr_local:
  web_dot_local:
