# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 23:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='metadata',
            field=models.ManyToManyField(blank=True, null=True, to='metadata.Metadatum'),
        ),
    ]
