# Generated by Django 2.0.7 on 2018-07-30 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('languages_plus', '0004_auto_20171214_0004'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceScan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.NullBooleanField()),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='languages_plus.Language')),
            ],
        ),
        migrations.RemoveField(
            model_name='resource',
            name='language',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='status',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='title',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='when_checked',
        ),
        migrations.AlterField(
            model_name='resourcedescription',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resource_descriptions', to='core.Resource'),
        ),
        migrations.AddField(
            model_name='resourcescan',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resoruce_scans', to='core.Resource'),
        ),
    ]
