# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 17:49
from __future__ import unicode_literals

from django.db import migrations, models



def expand_fields(apps, schema_editor):
    Project = apps.get_model('projects', 'Project')
    for old_status, new_status in {'a': 'Active',
                                   'i': 'Inactive',
                                   'd': 'Deleted'}.items():
        Project.objects.filter(status=old_status).update(status=new_status)

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='organization_type',
            field=models.CharField(blank=True, choices=[('Project', 'Project'), ('Museum', 'Museum'), ('Library', 'Library'), ('Datacenter', 'Datacenter'), ('Other', 'Other'), ('Laboratory', 'Laboratory'), ('Department', 'Department'), ('Archive', 'Archive'), ('Division', 'Division')], max_length=10, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='sector',
            field=models.CharField(blank=True, choices=[('Government', 'Government'), ('Non-Profit', 'Non-Profit'), ('Other', 'Other'), ('Corporate', 'Corporate'), ('Academic', 'Academic')], max_length=10, null=True, verbose_name='Sector'),
        ),
    ]
