# Generated by Django 2.0.4 on 2018-04-23 20:16

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='parent',
            new_name='parent_organization',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='created',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='deprecated',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='name',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='organization_type',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='sector',
        ),
        migrations.RemoveField(
            model_name='user',
            name='deprecated',
        ),
        migrations.RemoveField(
            model_name='user',
            name='description',
        ),
        migrations.AddField(
            model_name='organization',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organization',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='full_name',
            field=models.CharField(default='', max_length=2000, verbose_name='full legal name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='short_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='short name, nickname, or acronym'),
        ),
        migrations.AddField(
            model_name='organization',
            name='telephone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='url',
            field=core.models.NormalizedURLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description of mission and collecting policy'),
        ),
    ]
