# Generated by Django 2.0.7 on 2018-07-30 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180730_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcescan',
            name='redirect_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='resourcescan',
            unique_together={('resource', 'is_active', 'redirect_url')},
        ),
    ]
