# Generated by Django 2.0.4 on 2018-04-23 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180423_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='get_notification_emails',
            field=models.BooleanField(default=True),
        ),
    ]
