# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20171212_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='organization_type',
            field=models.CharField(blank=True, choices=[('Laboratory', 'Laboratory'), ('Library', 'Library'), ('Archive', 'Archive'), ('Museum', 'Museum'), ('Division', 'Division'), ('Datacenter', 'Datacenter'), ('Department', 'Department'), ('Project', 'Project'), ('Other', 'Other')], max_length=10, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='sector',
            field=models.CharField(blank=True, choices=[('Academic', 'Academic'), ('Non-Profit', 'Non-Profit'), ('Government', 'Government'), ('Other', 'Other'), ('Corporate', 'Corporate')], max_length=10, null=True, verbose_name='Sector'),
        ),
    ]
