# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170927_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.TextField(null=True, verbose_name='Name'),
        ),
    ]
