# Generated by Django 2.0.4 on 2018-04-23 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_get_notification_emails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='affiliations',
            field=models.ManyToManyField(blank=True, related_name='affiliated_users', to='core.Organization'),
        ),
    ]
