# Generated by Django 2.0.7 on 2018-07-31 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180730_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcedescription',
            name='author',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
