# Generated by Django 2.0.4 on 2018-04-23 23:13

import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180423_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='url',
            field=core.models.NormalizedURLField(blank=True, null=True),
        ),
    ]
