# Generated by Django 2.0.4 on 2018-04-24 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('languages_plus', '0004_auto_20171214_0004'),
        ('core', '0005_user_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='languages_plus.Language'),
        ),
        migrations.AddField(
            model_name='resource',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Redirected', 'Redirected'), ('Inactive', 'Inactive'), ('Unknown', 'Unknown')], default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='resource',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='when_checked',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='visibility',
            field=models.CharField(choices=[('Public', 'Public'), ('Project Members', 'Project Members'), ('Project Admins', 'Project Administrators')], default='Public', max_length=20),
        ),
    ]
