# Generated by Django 2.0.7 on 2018-08-07 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_resourcedescription_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcescan',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_scans', to='core.Resource', unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='resourcescan',
            unique_together=set(),
        ),
    ]
