# Generated by Django 2.1.1 on 2018-09-07 21:24

from django.db import migrations, models
from django.utils.text import slugify


def migrate_data_forward(apps, schema_editor):
    for instance in apps.get_model('core', 'Organization').objects.all():
        if instance.slug is None:
            instance.slug = slugify(instance.short_name or instance.full_name)
            instance.save()

def migrate_data_backward(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180807_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='slug',
            field=models.SlugField(null=True, unique=True, verbose_name='url'),
        ),
        migrations.RunPython(
            migrate_data_forward,
            migrate_data_backward,
        ),
        migrations.AlterField(
            model_name='organization',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='url'),
        ),
    ]
