# Generated by Django 2.0.4 on 2018-04-24 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180424_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourcescan',
            name='language',
        ),
        migrations.RemoveField(
            model_name='resourcescan',
            name='resource',
        ),
        migrations.DeleteModel(
            name='ResourceScan',
        ),
    ]
