# Generated by Django 2.0.4 on 2018-04-24 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20180424_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlScope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_time', models.PositiveIntegerField(blank=True, null=True)),
                ('max_size', models.PositiveIntegerField(blank=True, null=True)),
                ('max_resources', models.PositiveIntegerField(blank=True, null=True)),
                ('override_robot_exclusion', models.NullBooleanField(default=False)),
                ('boundary_behavior', models.CharField(blank=True, choices=[('Page', 'Page'), ('Site', 'Site'), ('Host', 'Host'), ('Domain', 'Domain')], max_length=200, null=True)),
                ('max_embedded_links', models.PositiveIntegerField(blank=True, null=True)),
                ('max_content_links', models.PositiveIntegerField(blank=True, null=True)),
                ('format_behavior', models.CharField(blank=True, choices=[('All', 'All'), ('PDF-Only', 'PDF-Only')], default='All', max_length=200, null=True)),
                ('technology', models.CharField(blank=True, choices=[('Archive-It', 'Archive-It'), ('Brozzler', 'Brozzler'), ('Crawler4j', 'Crawler4j'), ('Crawljax', 'Crawljax'), ('Heritrix', 'Heritrix'), ('HTTrack', 'HTTrack'), ('NetarchiveSuite', 'NetarchiveSuite'), ('Nutch', 'Nutch'), ('Social Feed Manager', 'Social Feed Manager'), ('WebRecorder', 'WebRecorder'), ('Wget', 'Wget'), ('Other', 'Other'), ('Unknown', 'Unknown')], default='Unknown', max_length=200, null=True)),
            ],
        ),
    ]
