# Generated by Django 2.1.1 on 2018-09-17 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('languages_plus', '0004_auto_20171214_0004'),
        ('core', '0008_auto_20180907_1631'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='resourcedescription',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='resourcedescription',
            name='asserted_by',
        ),
        migrations.RemoveField(
            model_name='resourcedescription',
            name='language',
        ),
        migrations.RemoveField(
            model_name='resourcedescription',
            name='resource',
        ),
        migrations.RemoveField(
            model_name='resourcedescription',
            name='subject_headings',
        ),
        migrations.RemoveField(
            model_name='resourcedescription',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='resourcescan',
            name='language',
        ),
        migrations.RemoveField(
            model_name='resourcescan',
            name='resource',
        ),
        migrations.RemoveField(
            model_name='resourcescan',
            name='tags',
        ),
        migrations.AddField(
            model_name='resource',
            name='author',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='is_active',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='resource',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='languages_plus.Language'),
        ),
        migrations.AddField(
            model_name='resource',
            name='on_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='redirect_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='tags',
            field=models.ManyToManyField(blank=True, to='core.Tag'),
        ),
        migrations.AddField(
            model_name='resource',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='ResourceDescription',
        ),
        migrations.DeleteModel(
            name='ResourceScan',
        ),
    ]
