# Generated by Django 2.1.1 on 2018-10-03 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20180928_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='slug',
            field=models.SlugField(help_text="Choose a URL for your organization's profile on Cobweb.", unique=True),
        ),
    ]
