# Generated by Django 2.0.5 on 2018-06-01 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20180510_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlscope',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.Organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crawlscope',
            name='title',
            field=models.CharField(default='abcd', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organization',
            name='full_name',
            field=models.CharField(max_length=2000, unique=True, verbose_name='full legal name'),
        ),
        migrations.AlterUniqueTogether(
            name='crawlscope',
            unique_together={('title', 'organization')},
        ),
    ]
