# Generated by Django 2.1.1 on 2018-10-03 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20181002_2016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='author',
            new_name='creator',
        ),
    ]
