# Generated by Django 2.0.5 on 2018-06-03 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20180601_1433'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjectheading',
            old_name='name',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='name',
            new_name='text',
        ),
    ]
