# Generated by Django 2.1.2 on 2019-01-03 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20181026_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='telephone_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
