# Generated by Django 2.0.5 on 2018-06-04 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20180603_0926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affiliation',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='affiliation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='affiliations',
        ),
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affiliated_users', to='core.Organization'),
        ),
        migrations.AddField(
            model_name='user',
            name='professional_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_for', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Affiliation',
        ),
    ]
