# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 01:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MDProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, db_index=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'MDProperties',
                'verbose_name': 'MDProperty',
            },
        ),
        migrations.CreateModel(
            name='MDVocabulary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_index=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'MDVocabularies',
                'verbose_name': 'MDVocabulary',
            },
        ),
        migrations.CreateModel(
            name='Metadatum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_index=True)),
                ('md_property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='metadata.MDProperty')),
            ],
        ),
        migrations.AddField(
            model_name='mdproperty',
            name='vocabulary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='metadata.MDVocabulary'),
        ),
        migrations.AlterUniqueTogether(
            name='metadatum',
            unique_together=set([('md_property', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='mdproperty',
            unique_together=set([('vocabulary', 'name')]),
        ),
    ]
