# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 20:55
from django.db import migrations


def name_to_title(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    for model in (apps.get_model('projects', 'Project'), apps.get_model('archives', 'Collection')):
        for obj in model.objects.all():
            obj.title = obj.name
            obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(name_to_title),
    ]
