# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0002_auto_20170927_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mdproperty',
            name='name',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='mdvocabulary',
            name='name',
            field=models.TextField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='metadatum',
            name='name',
            field=models.TextField(db_index=True),
        ),
    ]
