# Generated by Django 2.0.5 on 2018-06-04 22:22

import cobweb.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIEndpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('last_updated', models.DateTimeField(editable=False, null=True)),
            ],
            options={
                'verbose_name': 'API Endpoint',
            },
            bases=(cobweb.models.CobwebModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ImportedRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=200)),
                ('record_type', models.CharField(max_length=200)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField()),
                ('parents', models.ManyToManyField(blank=True, related_name='children', to='webarchives.ImportedRecord')),
            ],
            bases=(cobweb.models.CobwebModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='OAIPMHEndpoint',
            fields=[
                ('apiendpoint_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='webarchives.APIEndpoint')),
            ],
            options={
                'verbose_name': 'OAI-PMH Endpoint',
            },
            bases=('webarchives.apiendpoint',),
        ),
        migrations.AddField(
            model_name='importedrecord',
            name='source_feed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webarchives.APIEndpoint'),
        ),
        migrations.AddField(
            model_name='apiendpoint',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Organization'),
        ),
        migrations.AddField(
            model_name='apiendpoint',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_webarchives.apiendpoint_set+', to='contenttypes.ContentType'),
        ),
        migrations.CreateModel(
            name='BaseAITEndpoint',
            fields=[
                ('oaipmhendpoint_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='webarchives.OAIPMHEndpoint')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('webarchives.oaipmhendpoint',),
        ),
        migrations.AlterUniqueTogether(
            name='importedrecord',
            unique_together={('source_feed', 'identifier')},
        ),
        migrations.CreateModel(
            name='AITCollectionsEndpoint',
            fields=[
                ('baseaitendpoint_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='webarchives.BaseAITEndpoint')),
            ],
            options={
                'verbose_name': 'Archive-It Master OAI-PMH Endpoint',
            },
            bases=('webarchives.baseaitendpoint',),
        ),
        migrations.CreateModel(
            name='AITPartnerEndpoint',
            fields=[
                ('baseaitendpoint_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='webarchives.BaseAITEndpoint')),
            ],
            options={
                'verbose_name': 'Archive-It Partner OAI-PMH Endpoint',
            },
            bases=('webarchives.baseaitendpoint',),
        ),
    ]
