# Generated by Django 2.0.5 on 2018-06-08 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webarchives', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importedrecord',
            name='identifier',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
