# Generated by Django 2.0.5 on 2018-06-10 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webarchives', '0003_importedrecord_resource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importedrecord',
            name='identifier',
            field=models.CharField(max_length=2000, unique=True),
        ),
        migrations.AlterField(
            model_name='importedrecord',
            name='record_type',
            field=models.CharField(max_length=2000),
        ),
    ]
