# Generated by Django 2.0.5 on 2018-06-12 17:31

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webarchives', '0004_auto_20180609_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importedrecord',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
