# Generated by Django 2.1.1 on 2018-09-10 22:08

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webarchives', '0005_auto_20180612_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importedrecord',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
