# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 19:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cobweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceMD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='agent',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resourcemd',
            name='asserted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cobweb.Agent'),
        ),
        migrations.AddField(
            model_name='resourcemd',
            name='describes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cobweb.Resource'),
        ),
        migrations.AlterUniqueTogether(
            name='resourcemd',
            unique_together=set([('describes', 'asserted_by')]),
        ),
    ]
