# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobweb', '0002_auto_20170823_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='name',
            field=models.CharField(default='Test Collection', max_length=200, verbose_name='Name'),
            preserve_default=False,
        ),
    ]
