# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-06 18:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cobweb', '0002_auto_20170906_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='software',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cobweb.Software'),
            preserve_default=False,
        ),
    ]
