# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-06 21:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cobweb', '0004_auto_20170906_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentidentifier',
            name='agent',
        ),
        migrations.DeleteModel(
            name='AgentIdentifier',
        ),
    ]
