# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobweb', '0004_auto_20170825_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentidentifier',
            name='id_type',
            field=models.CharField(choices=[('OTH', 'Other'), ('SCO', 'Scopus'), ('TWI', 'Twitter Handle'), ('RID', 'ResearcherID'), ('ORC', 'ORCID')], max_length=3, verbose_name='Type'),
        ),
    ]
