# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 00:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cobweb', '0006_user_description'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='institutionmd',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='institutionmd',
            name='asserted_by',
        ),
        migrations.RemoveField(
            model_name='institutionmd',
            name='describes',
        ),
        migrations.AddField(
            model_name='institution',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date Created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='institution',
            name='deprecated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date Deprecated'),
        ),
        migrations.AddField(
            model_name='institution',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='institution',
            name='institution_type',
            field=models.CharField(blank=True, choices=[('arc', 'Archive'), ('dat', 'Datacenter'), ('dpt', 'Department'), ('div', 'Division'), ('lab', 'Laboratory'), ('lib', 'Library'), ('mus', 'Museum'), ('pro', 'Project'), ('oth', 'Other')], max_length=3, null=True, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='institution',
            name='sector',
            field=models.CharField(blank=True, choices=[('a', 'Academic'), ('c', 'Corporate'), ('g', 'Government'), ('n', 'Non-Profit'), ('o', 'Other')], max_length=1, null=True, verbose_name='Sector'),
        ),
        migrations.AlterField(
            model_name='institutionidentifier',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cobweb.Institution'),
        ),
        migrations.RemoveField(
            model_name='agent',
            name='created',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='deprecated',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='description',
        ),
        migrations.AlterUniqueTogether(
            name='agent',
            unique_together=set([('user', 'software')]),
        ),
        migrations.DeleteModel(
            name='InstitutionMD',
        ),
    ]
