# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobweb', '0006_auto_20170825_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='agent_type',
            field=models.CharField(choices=[('a', 'Automated'), ('p', 'Person')], default='p', max_length=3, verbose_name='Type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='institutionmd',
            name='institution_type',
            field=models.CharField(blank=True, choices=[('arc', 'Archive'), ('dat', 'Datacenter'), ('dpt', 'Department'), ('div', 'Division'), ('lab', 'Laboratory'), ('lib', 'Library'), ('mus', 'Museum'), ('pro', 'Project'), ('oth', 'Other')], max_length=3, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='institutionmd',
            name='sector',
            field=models.CharField(blank=True, choices=[('a', 'Academic'), ('c', 'Corporate'), ('g', 'Government'), ('n', 'Non-Profit'), ('o', 'Other')], max_length=1, null=True, verbose_name='Sector'),
        ),
    ]
