# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 02:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('cobweb', '0007_auto_20170912_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetadataRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('metadata', models.TextField()),
                ('asserted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cobweb.Agent')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='MetadataType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='metadatarecord',
            name='metadata_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cobweb.MetadataType'),
        ),
    ]
