# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 23:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cobweb', '0007_auto_20170825_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionIdentifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_type', models.CharField(choices=[('i', 'ISNI'), ('r', 'Ringgold'), ('o', 'Other')], max_length=3, verbose_name='Type')),
                ('value', models.CharField(max_length=200, verbose_name='Value')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cobweb.InstitutionMD')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='collectionmd',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='collectionmd',
            name='asserted_by',
        ),
        migrations.RemoveField(
            model_name='collectionmd',
            name='describes',
        ),
        migrations.AlterUniqueTogether(
            name='projectmd',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='projectmd',
            name='asserted_by',
        ),
        migrations.RemoveField(
            model_name='projectmd',
            name='describes',
        ),
        migrations.AlterUniqueTogether(
            name='resourcemd',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='resourcemd',
            name='asserted_by',
        ),
        migrations.RemoveField(
            model_name='resourcemd',
            name='describes',
        ),
        migrations.AddField(
            model_name='collection',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date Created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collection',
            name='deprecated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date Deprecated'),
        ),
        migrations.DeleteModel(
            name='CollectionMD',
        ),
        migrations.DeleteModel(
            name='ProjectMD',
        ),
        migrations.DeleteModel(
            name='ResourceMD',
        ),
    ]
