# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobweb', '0008_auto_20170912_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='metadatatype',
            name='name',
            field=models.CharField(default='unknown', max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='tags',
            field=models.ManyToManyField(to='cobweb.Tag'),
        ),
        migrations.AddField(
            model_name='collection',
            name='tags',
            field=models.ManyToManyField(to='cobweb.Tag'),
        ),
        migrations.AddField(
            model_name='holding',
            name='tags',
            field=models.ManyToManyField(to='cobweb.Tag'),
        ),
        migrations.AddField(
            model_name='institution',
            name='tags',
            field=models.ManyToManyField(to='cobweb.Tag'),
        ),
        migrations.AddField(
            model_name='nomination',
            name='tags',
            field=models.ManyToManyField(to='cobweb.Tag'),
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(to='cobweb.Tag'),
        ),
        migrations.AddField(
            model_name='resource',
            name='tags',
            field=models.ManyToManyField(to='cobweb.Tag'),
        ),
        migrations.AddField(
            model_name='software',
            name='tags',
            field=models.ManyToManyField(to='cobweb.Tag'),
        ),
        migrations.AddField(
            model_name='user',
            name='tags',
            field=models.ManyToManyField(to='cobweb.Tag'),
        ),
    ]
