# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 18:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cobweb', '0009_Tag_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='archiveit_identifier',
            field=models.URLField(blank=True, editable=False, null=True, unique=True, verbose_name='Archive-It.org Identifier'),
        ),
        migrations.AddField(
            model_name='institution',
            name='archiveit_identifier',
            field=models.URLField(blank=True, editable=False, null=True, unique=True, verbose_name='Archive-It.org Identifier'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cobweb.Institution'),
        ),
    ]
