# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 18:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cobweb', '0010_auto_20170913_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='institution',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cobweb.Institution'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='collection',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Name'),
        ),
    ]
