# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 18:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cobweb', '0011_auto_20170913_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='software',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cobweb.Software'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='collection',
            name='institution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cobweb.Institution'),
        ),
        migrations.AlterField(
            model_name='institutionidentifier',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cobweb.Institution'),
        ),
    ]
