# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobweb', '0012_auto_20170913_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='Name'),
        ),
    ]
