# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 20:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cobweb', '0013_auto_20170913_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIEndpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cobweb.Institution')),
            ],
        ),
        migrations.CreateModel(
            name='APIProtocol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('uri', models.URLField(null=True, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='apiendpoint',
            name='protocol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cobweb.APIProtocol'),
        ),
    ]
