# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 20:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cobweb', '0015_auto_20170913_1345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='name',
            new_name='tag_value',
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together=set([('tag_property', 'tag_value')]),
        ),
    ]
