# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobweb', '0016_auto_20170913_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
    ]
