# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 21:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cobweb', '0018_auto_20170913_1538'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='holding',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='nomination',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='project',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='software',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tags',
        ),
    ]
