# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobweb', '0019_auto_20170918_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='archiveit_identifier',
            field=models.URLField(blank=True, null=True, unique=True, verbose_name='Archive-It.org Identifier'),
        ),
    ]
