# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 21:02
from __future__ import unicode_literals

from django.db import migrations

def delete_collections_without_http_url(apps, schema_editor):
	"""Delete all Collection rows where .archiveit_identifier doesn't start with http://
	(Mainly targeted at https:// duplicates.)"""
	( apps.get_model('cobweb', 'Collection').objects
		.exclude(archiveit_identifier__startswith="http://")
		.delete() )

class Migration(migrations.Migration):

    dependencies = [
        ('cobweb', '0020_auto_20170920_1301'),
    ]

    operations = [
    	migrations.RunPython(delete_collections_without_http_url),
    ]
