# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 10:46
from __future__ import unicode_literals

import cobweb.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cobweb', '0021_auto_20170920_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='archiveit_identifier',
            field=cobweb.models.NocryptoURLField(blank=True, null=True, unique=True, verbose_name='Archive-It.org Identifier'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cobweb.Institution'),
        ),
    ]
