# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 10:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cobweb', '0022_auto_20170921_0346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='archiveit_identifier',
            new_name='identifier',
        ),
        migrations.RenameField(
            model_name='institution',
            old_name='archiveit_identifier',
            new_name='identifier',
        ),
    ]
