# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 11:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cobweb', '0023_auto_20170921_0349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apiendpoint',
            old_name='url',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='apiprotocol',
            old_name='uri',
            new_name='identifier',
        ),
        migrations.RenameField(
            model_name='metadatatype',
            old_name='url',
            new_name='identifier',
        ),
    ]
