# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobweb', '0024_auto_20170921_0401'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='raw_metadata',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='holding',
            name='raw_metadata',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='raw_metadata',
            field=models.TextField(blank=True, null=True),
        ),
    ]
