# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 11:19
from __future__ import unicode_literals

from django.db import migrations

def copy_MetadataRecord_into_textfield(apps, schema_editor):
	"""This version didn't work. The actual data migration happens in 0027."""
	pass

	# success, fail = 0,0
	# for md_record in apps.get_model('cobweb', 'MetadataRecord').objects.all():
	# 	try:
	# 		md_record.object_described.raw_metadata = md_record.metadata
	# 		md_record.object_described.save()
	# 		success += 1
	# 	except:
	# 		fail += 1
	# print("{} / {}".format(success, fail))


class Migration(migrations.Migration):

    dependencies = [
        ('cobweb', '0025_auto_20170921_0416'),
    ]

    operations = [
    	migrations.RunPython(copy_MetadataRecord_into_textfield),
    ]
