# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 12:22
from __future__ import unicode_literals

from django.db import migrations


def copy_MetadataRecord_into_textfield(apps, schema_editor):
	"""Copy raw metadata records from their own objects into textfield
	of object described."""

	success, fail = 0,0
	for md_record in apps.get_model('cobweb', 'MetadataRecord').objects.all():
		try:
			model_name = md_record.content_type.model
			object_id = md_record.object_id
			object_described = apps.get_model('cobweb', model_name).objects.get(id=object_id)
			object_described.raw_metadata = md_record.metadata
			object_described.save()
			success += 1
		except:
			fail += 1
	print("{} / {} MetadataRecords linked to objects.".format(success, fail))


class Migration(migrations.Migration):

    dependencies = [
        ('cobweb', '0026_auto_20170921_0419'),
    ]

    operations = [
    	migrations.RunPython(copy_MetadataRecord_into_textfield),
    ]