# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 12:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cobweb', '0027_auto_20170921_0522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metadatarecord',
            name='asserted_by',
        ),
        migrations.RemoveField(
            model_name='metadatarecord',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='metadatarecord',
            name='metadata_type',
        ),
        migrations.DeleteModel(
            name='MetadataRecord',
        ),
        migrations.DeleteModel(
            name='MetadataType',
        ),
    ]
