# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 15:00
from __future__ import unicode_literals

import cobweb.models
from django.db import migrations


def decrypt_resource_urls(apps, schema_editor):
    """replace e.g. https:// with http:// (Didn't work, just re-import)."""

    success, fail = 0, 0
    for this_resource in apps.get_model('cobweb', 'Resource').objects.all():
        location = cobweb.models.nocrypto_url(this_resource.root_url)
        try:
            this_resource.location = location
            success += 1
        except:
            fail += 1

    print("{} created, {} failed".format(success,fail))

class Migration(migrations.Migration):

    dependencies = [
        ('cobweb', '0028_auto_20170921_0542'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='location',
            field=cobweb.models.NocryptoURLField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='identifier',
            field=cobweb.models.NocryptoURLField(blank=True, null=True, unique=True),
        ),
        migrations.RunPython(decrypt_resource_urls),
    ]
