# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 15:38
from __future__ import unicode_literals

import cobweb.models
from django.db import migrations


def delete_null_location_urls(apps, schema_editor):
    """Delete resources with null "location". Which is all of them, I'll re-harvest."""
    apps.get_model('cobweb', 'Resource').objects.filter(location__isnull=True).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('cobweb', '0029_auto_20170921_0800'),
    ]

    operations = [
        migrations.RunPython(delete_null_location_urls),
    ]
