# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 15:45
from __future__ import unicode_literals

import cobweb.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cobweb', '0030_auto_20170921_0838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='root_url',
        ),
        migrations.AlterField(
            model_name='resource',
            name='location',
            field=cobweb.models.NocryptoURLField(unique=True),
        ),
    ]
