# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 19:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cobweb', '0032_institution_parents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='parents',
        ),
    ]
