# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 20:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cobweb', '0033_remove_institution_parents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='asserted_by',
        ),
        migrations.RemoveField(
            model_name='holding',
            name='asserted_by',
        ),
    ]
