from pathlib import Path

from django.conf import settings

from core.models import Resource, Tag, User
from projects.models import Project, Nomination

FAKE_NEWS_PROJECT = Project.objects.get_or_create(
    title="Propaganda, disinformation, parody, dismissal: Making sense of \"Fake News\".",
    defaults={
        "description": "This project captures and categorizes online sources that purport to provide news coverage of current events.",
        "nomination_policy": "Public",
        "status": "Open",
        # "administrators": User.objects.get_or_create(username="andy")[0],
    }
)[0]

def import_fake_news(proj, data):
    for (url, tags) in data.items():
        res = Resource.objects.get_or_create(url=url)[0]
        (nom, created) = Nomination.objects.get_or_create(project=proj, resource=res)
        for tag in tags:
            nom.tags.add(Tag.objects.get_or_create(title=tag)[0])
        print(nom, created, nom.tags.all())

import_fake_news(
    FAKE_NEWS_PROJECT,
    {
    	'100percentfedup.com': ['bias'],
        '21stcenturywire.com': ['conspiracy'],
        '24newsflash.com': ['fake'],
        '365usanews.com': ['bias', 'conspiracy'],
        '4threvolutionarywar.wordpress.com': ['bias', 'conspiracy'],
        '70news.wordpress.com': ['fake'],
        '82.221.129.208': ['conspiracy', 'fake'],
        'aanirfan.blogspot.co.uk': ['unreliable'],
        'abcnews.com.co': ['fake'],
        'abcnewsgo.co': ['fake'],
        'abeldanger.net': ['conspiracy'],
        'abovetopsecret.com': ['conspiracy', 'rumor'],
        'abriluno.com': ['satire', 'fake'],
        'aceflashman.wordpress.com': ['satire'],
        'Acting­Man.com': ['unreliable', 'conspiracy'],
        'activistpost.com': ['conspiracy'],
        'addictinginfo.org': ['clickbait', 'unreliable'],
        'adobochronicles.com': ['fake'],
        'advocate.com': ['political', 'credible'],
        'aheadoftheherd.com': [],
        'ahtribune.com': ['unreliable', 'bias'],
        'allnewspipeline.com': ['unreliable', 'conspiracy'],
        'Alt­Market.com': [],
        'alternet.org': ['political', 'credible'],
        'americanblog.com': [],
        'americanfreepress.net': ['conspiracy', 'bias'],
        'AmericanKabuki.blogspot.com': ['junksci'],
        'americanlookout.com': ['bias', 'clickbait'],
        'americannews.com': ['fake'],
        'americanoverlook.com': ['fake'],
        'americanpatriotdaily.com': ['bias', 'clickbait', 'bias'],
        'americanprogress.org': [],
        'americanreviewer.com': ['conspiracy'],
        'americantoday.news': ['rumor', 'bias'],
        'americasfreedomfighters.com': ['bias', 'clickbait'],
        'AmmoLand.com': ['bias'],
        'amplifyingglass.com': ['clickbait', 'satire'],
        'amren.com': ['hate', 'conspiracy'],
        'amtvmedia.com': ['rumor', 'unreliable'],
        'amusmentic.com': ['clickbait', 'rumor'],
        'ancient­code.com': ['junksci', 'unreliable'],
        'angrypatriotmovement.com': ['conspiracy'],
        'anonews.co': ['unreliable'],
        'anonhq.com': ['unreliable'],
        'anonnews.co': ['unreliable'],
        'anotherdayintheempire.com': ['bias', 'conspiracy'],
        'antiwar.com': ['bias', 'unreliable'],
        'antoniusaquinas.wp.com': ['bias', 'conspiracy'],
        'ArmstrongEconomics.com': [],
        'asia­pacificresearch.com': ['unreliable', 'satire'],
        'assassinationscience.com': ['conspiracy', 'junksci'],
        'associatedmediacoverage.com': ['satire'],
        'attn.com': ['political', 'clickbait'],
        'AutomaticEarth.com': ['unreliable'],
        'automotostar.com': ['clickbait'],
        'awarenessact.com': ['conspiracy', 'junksci'],
        'awazetribune.com': [],
        'awdnews.com': ['conspiracy'],
        'awm.com': ['unreliable', 'bias', 'clickbait'],
        'BadSquad.com': [],
        'baptistnews.com': [],
        'barenakedislam.com': ['hate'],
        'Barnhardt.biz': [],
        'BB4SP.com': ['conspiracy', 'bias', 'bias'],
        'beehivebugle.com': ['satire'],
        'beforeitsnews.com': ['fake', 'conspiracy', 'rumor'],
        'betootaadvocate.com': ['satire'],
        'bients.com': ['clickbait'],
        'bigamericannews.com': ['satire', 'fake'],
        'bigbluedimension.com': ['rumor', 'bias'],
        'bigbluevision.com': ['hate'],
        'bigbluevision.org': ['clickbait', 'bias'],
        'bighairynews.com': ['fake', 'conspiracy'],
        'bignuggetnews.com': ['bias', 'rumor'],
        'bigpzone.com': [],
        'bipartisanreport.com': ['clickbait', 'bias'],
        'blackagendareport.com': ['unreliable'],
        'blackgenocide.org': [],
        'blacklistednews.com': ['clickbait', 'unreliable'],
        'blog.uncommonwisdomdaily.com': [],
        'bluenationreview.com': ['clickbait', 'unreliable'],
        'Boilingfrogspost.com': ['unreliable'],
        'borowitzreport.com': ['satire'],
        'bostonleader.com': ['fake'],
        'breaking911.com': ['clickbait', 'unreliable'],
        'breakpoint.org': [],
        'breitbart.com': ['political', 'unreliable', 'bias'],
        'BrotherJohnF.com': ['bias', 'conspiracy'],
        'BullionBullsCanada.com': ['conspiracy'],
        'burrardstreetjournal.com': ['satire'],
        'buzzfeedusa.com': ['fake', 'rumor'],
        'bvanews.com': ['unreliable', 'bias', 'fake'],
        'callthecops.net': ['satire'],
        'canadafreepress.com': ['conspiracy', 'bias'],
        'cap­news.com': ['fake'],
        'CaseyResearch.com': [],
        'cbsnews.com.co': ['fake'],
        'celebtricity.com': ['satire'],
        'centerforsecuritypolicy.org': [],
        'channel­7­news.com/': ['fake'],
        'charismanews.com': [],
        'chaser.com.au': ['satire'],
        'checkoutthehealthyworld.com': ['junksci', 'clickbait'],
        'chicksontheright.com': ['clickbait', 'bias'],
        'christianfightback.com': ['hate', 'bias'],
        'christianpost.com': [],
        'christiantimesnewspaper.com': ['rumor', 'bias'],
        'christwire.org': ['satire'],
        'chronicle.su': ['satire'],
        'chroniclesmagazine.org': [],
        'citizensunited.org': [],
        'city­journal.org': [],
        'cityworldnews.com': ['fake'],
        'civictribune.com': ['fake'],
        'clashdaily.com': ['fake', 'conspiracy', 'bias'],
        'clickhole.com': ['satire'],
        'cnnnext.com': ['unreliable'],
        'CNSNews.com': ['unreliable', 'bias'],
        'coasttocoastam.com': ['unreliable'],
        'Coinflation.com': [],
        'collective­evolution.com': ['junksci'],
        'collectivelyconscious.net': ['junksci', 'conspiracy'],
        'ComingDepression.com': [],
        'commentarymagazine.com': [],
        'commondreams.org': ['political', 'clickbait'],
        'concisepolitics.com': ['conspiracy', 'hate'],
        'consciouslifenews.com': ['junksci'],
        'conservapedia.com': [],
        'conservativebyte.com': ['fake', 'bias'],
        'conservativedailypost.com': ['fake', 'unreliable'],
        'conservativefiringline.com': ['bias', 'conspiracy', 'clickbait'],
        'conservativefrontline.com': [],
        'conservativehq.com': [],
        'conservativeinfidel.com': ['fake', 'conspiracy'],
        'conservativeoutfitters.com': ['unreliable', 'clickbait'],
        'conservativepapers.com': [],
        'conservativerefocus.com': ['conspiracy'],
        'conservativereview.com': [],
        'conservativespirit.com': ['bias'],
        'conservativestate.com': ['bias'],
        'conservativetribune.com': ['bias', 'conspiracy', 'unreliable'],
        'consortiumnews.com': ['credible'],
        'conspiracyplanet.com': [],
        'conspiracywire.com': ['conspiracy'],
        'corbettreport.com': ['conspiracy', 'bias'],
        'countdowntozerotime.com': ['conspiracy'],
        'countercurrents.org': ['political', 'unreliable'],
        'counterinformation.wordpress.com': ['political'],
        'counterpsyops.com': ['conspiracy'],
        'counterpunch.com': ['political'],
        'counterpunch.org': ['political'],
        'cowgernation.com': ['bias', 'conspiracy'],
        'creambmp.com': ['satire', 'fake'],
        'cryptogon.com': [],
        'crystalair.com': ['satire'],
        'dailybuzzlive.com': ['fake'],
        'dailycurrant.com': ['satire'],
        'dailydiscord.com': ['satire'],
        'dailyheadlines.com': ['fake'],
        'dailyheadlines.net': ['fake'],
        'dailykos.com': ['political', 'clickbait', 'credible'],
        'dailyleak.org': ['parody', 'fake'],
        'dailynewsbin.com': ['bias', 'clickbait'],
        'dailynewspolitic.com': [],
        'dailyoccupation.com': ['conspiracy', 'bias'],
        'dailypolitics.info': [],
        'dailypoliticsusa.com': ['bias'],
        'dailysignal.com': ['bias'],
        'dailysquib.co.uk': ['satire'],
        'dailystormer.com': ['hate', 'conspiracy', 'bias'],
        'dailytelegraph.com.au': [],
        'dailywire.com': ['bias'],
        'dandygoat.com': ['satire'],
        'darkmoon.me': ['hate', 'bias'],
        'darkpolitricks.com': ['bias', 'conspiracy'],
        'dataasylum.com': [],
        'DaveJanda.com': ['unreliable'],
        'davidduke.com': ['hate'],
        'davidstockmanscontracorner.com': ['political'],
        'davidwolfe.com': ['conspiracy'],
        'dcclothesline.com': ['conspiracy', 'junkscience'],
        'dcgazette.com': ['fake'],
        'dcleaks.com': ['unreliable'],
        'DeadLineLive.info': [],
        'DeadlyClear.wordpress.com': [],
        'debunkingskeptics.com': [],
        'defenddemocracy.press': ['bias', 'political'],
        'delectabledietofpics.net': [],
        'dennismichaellynch.com': ['political'],
        'denverguardian.com': ['fake'],
        'departed.co': ['fake'],
        'der­postillon.com': ['satire'],
        'derfmagazine.com': ['satire'],
        'DeviantInvestor.com': [],
        'dineal.com': ['junksci'],
        'disclose.tv': ['satire', 'conspiracy'],
        'disclosuremedia.net': ['conspiracy'],
        'discoverthenetworks.org': [],
        'discovery.org': [],
        'dissentmagazine.org': ['political'],
        'diversitychronicle.wordpress.com': ['satire'],
        'doctorhousingbubble.com': [],
        'DollarVigilante.com': ['bias'],
        'donaldtrumpnews.co': ['fake'],
        'Dont­Tread­On.Me': ['conspiracy'],
        'downtrend.com': ['fake', 'satire'],
        'DProgram.net': [],
        'drudgereport.com': ['bias', 'bias'],
        'drudgereport.com.co': ['fake'],
        'duffleblog.com': ['satire'],
        'duhprogressive.com': ['satire'],
        'Dutchsinse.com': ['conspiracy'],
        'EagleRising.com': ['bias', 'clickbait'],
        'EbolaHoax.com': ['conspiracy'],
        'economicnoise.com': [],
        'ecowatch.com': [],
        'EdgeTraderPlus.com': [],
        'educate­yourself.org': ['conspiracy', 'junksci'],
        'educateinspirechange.org/health': ['clickbait', 'junksci'],
        'electionnightgatekeepers.com': ['conspiracy', 'unreliable'],
        'elelephantintheroom.blogspot.com': ['bias'],
        'elitereaders.com': ['clickbait'],
        'elkoshary.com': ['satire'],
        'elmundotoday.com': ['satire'],
        'embols.com': ['fake'],
        'empireherald.com': ['fake', 'satire'],
        'empirenews.net': ['fake', 'satire'],
        'empiresports.co': ['satire'],
        'Emptywheel.net': ['political'],
        'enabon.com': ['fake'],
        'endingthefed.com': ['bias'],
        'endoftheamericandream.com': [],
        'endtime.com': [],
        'enduringvision.com': ['fake'],
        'english.ruvr.ru': [],
        'EUTimes.net': ['hate', 'conspiracy'],
        'eutopia.buzz': ['fake', 'satire', 'conspiracy'],
        'everydayworldnews.com': [],
        'everythingnewdaily.com': [],
        'ewao.com': ['junksci'],
        'ExperimentalVaccines.org': [],
        'ExplosiveReports.Com': [],
        'Expose1933.com': ['conspiracy', 'hate'],
        'express.co.uk': [],
        'extraclubmagazine.com': ['bias', 'clickbait', 'fake'],
        'eyeopening.info': ['conspiracy', 'junksci'],
        'fairus.org': [],
        'fakingnews.com': ['fake', 'satire'],
        'familysecuritymatters.org': ['conspiracy', 'bias'],
        'fantasticword.com': [],
        'FarmWars.info': [],
        'federalistpress.com': ['bias'],
        'fellowshipoftheminds.com': ['conspiracy', 'junksci'],
        'filmsforaction.org': ['political'],
        'FinancialSense.com': [],
        'FinancialSurvivalNetwork.com': ['unreliable', 'bias'],
        'firearmscoalition.org': [],
        'floridasunpost.com': ['fake', 'satirical'],
        'flyheight.com': [],
        'fmobserver.com': ['satire'],
        'fognews.ru': ['satire'],
        'foodbabe.com': ['junksci'],
        'foreignpolicyjournal.com': ['political'],
        'fort­russ.com': [],
        'fourwinds10.net': ['conspiracy', 'junksci'],
        'fprnradio.com': ['conspiracy', 'fake'],
        'freakoutnation.com': ['bias'],
        'FreeBeacon.com': ['bias'],
        'freedomdaily.com': ['fake'],
        'FreedomForceInternational.com': ['conspiracy'],
        'freedomoutpost.com': ['conspiracy', 'bias'],
        'FreedomsPhoenix.com': ['bias', 'conspiracy'],
        'freedomworks.org': [],
        'FreemansPerspective.com': [],
        'freepatriot.org': ['satire'],
        'FreeStateProject.org': [],
        'freewoodpost.com': ['satire'],
        'fridaymash.com': ['satire'],
        'fromthetrenchesworldreport.com': ['conspiracy', 'junksci', 'bias'],
        'frontpagemag.com': ['bias', 'hate'],
        'FTMDaily.com': [],
        'FullSpectrumDominance.com': [],
        'fusion.net': ['political'],
        'gaia.com': ['conspiracy', 'junksci'],
        'gainspainscapital.com': [],
        'galacticconnection.com': ['junksci'],
        'gangstergovernment.com': ['conspiracy', 'bias'],
        'GATA.org': [],
        'gatesofvienna.net': ['hate', 'conspiracy'],
        'geoengineeringwatch.org': ['junksci', 'conspiracy'],
        'geopolmonitor.com': ['political'],
        'GlobalEconomicAnalysis.com': [],
        'globalresearch.ca': ['conspiracy'],
        'GlobalWealthProtection.com': [],
        'GloomBoomDoom.com': [],
        'glossynews.com': ['satire'],
        'godlikeproductions.com': ['conspiracy'],
        'GoldBroker.com': [],
        'GoldCore.com': [],
        'GoldMoney.com': [],
        'GoldSeek.com': [],
        'GoldSilver.com': [],
        'GoldSilverBitcoin.com': [],
        'GoldSilverWorlds.com': [],
        'GoldSwitzerland.com': [],
        'golemxiv.co.uk': [],
        'gomerblog.com': ['satire'],
        'goneleft.com': ['fake'],
        'GonzaloLira.Blogspot.com': [],
        'gopthedailydose.com': ['fake', 'conspiracy', 'bias'],
        'govtslaves.info': ['conspiracy'],
        'greanvillepost.com': ['conspiracy'],
        'GreenMedInfo.com': [],
        'guardianlv.com': ['political'],
        'guccifer2.wordpress.com': ['unreliable'],
        'gulagbound.com': ['bias'],
        'hangthebankers.com': ['bias', 'conspiracy'],
        'healthimpactnews.com': ['junksci', 'bias'],
        'healthnutnews.com': ['junksci'],
        'healthy­holistic­living.com': [],
        'heamericanconservative.com': [],
        'heartland.org': [],
        'heatst.com': ['bias'],
        'helastlineofdefense.org': [],
        'HendersonLeftHook.wordpress.com': [],
        'henrymakow.com': ['fake', 'conspiracy'],
        'herebel.media.com': [],
        'heresyblog.net': ['bias', 'conspiracy', 'rumor'],
        'heritage.org': [],
        'holyobserver.com': ['satire'],
        'horowitzfreedomcenter.org': [],
        'HowToVanish.com': [],
        'hudson.org': [],
        'humansarefree.com': ['conspiracy'],
        'humortimes.com': ['satire'],
        'huzlers.com': ['satire'],
        'ibankcoin.com/flyblog/': [],
        'icr.org': [],
        'ifyouonlynews.com': ['unreliable', 'satire'],
        'ihavethetruth.com': ['bias', 'clickbait', 'fake'],
        'ijr.com': ['bias', 'unreliable'],
        'illuminati­news.com': [],
        'ilovemyfreedom.org': ['bias', 'clickbait'],
        'in5d.com': ['junksci'],
        'indiaarising.com': ['clickbait', 'unreliable'],
        'infiniteunknown.net': [],
        'informationclearinghouse.info': ['conspiracy', 'unreliable'],
        'informetoday.com': ['bias', 'unreliable'],
        'infostormer.com': ['fake', 'hate', 'conspiracy'],
        'infowars.com': ['conspiracy'],
        'instaworldnews.com': ['bias'],
        'intellihub.com': ['conspiracy', 'unreliable'],
        'InternationalMan.com': [],
        'intrendtoday.com': ['fake', 'clickbait'],
        'intrepidreport.com': ['bias'],
        'investmentresearchdynamics.com': ['conspiracy'],
        'investmentwatchblog.com': ['bias', 'fake'],
        'ironictimes.com': ['satire'],
        'islamicanews.com': ['satire'],
        'itaglive.com': ['fake'],
        'ITCCS.org': [],
        'ItMakesSenseBlog.com': ['fake'],
        'iwanttoexplore.com': ['fake'],
        'jackpineradicals.com': ['political'],
        'jacobinmag.com': ['political'],
        'jamesrgrangerjr.com': ['bias'],
        'jessescrossroadscafe.blogspot.com': [],
        'jesus­is­savior.com': ['conspiracy'],
        'jewsnews.co.il': ['unreliable', 'bias', 'clickbait'],
        'jihadwatch.org': [],
        'JohnGaltfla.com': [],
        'johngaltfla.com/wordpress': [],
        'johnnyrobish.com': ['satire'],
        'jonesreport.com': ['conspiracy'],
        'jookos.com': [],
        'journal­neo.org': ['bias'],
        'JSMineset.com': [],
        'judicialwatch.org': [],
        'katehon.com': ['bias'],
        'katehon.org': [],
        'Kauilapele.com': [],
        'kereport.com': [],
        'kingworldnews.com': [],
        'knowledgeoftoday.org': [],
        'landoverbaptist.org': ['satire'],
        'LaRouchePac.com': [],
        'leap2020.eu': [],
        'legorafi.fr': [],
        'lewrockwell.com': ['bias', 'unreliable'],
        'LFB.org': [],
        'lfb.org': [],
        'liberalamerica.org': ['clickbait', 'bias'],
        'liberalbias.com': ['satire'],
        'liberaldarkness.com': ['satire', 'fake'],
        'libertyblitzkrieg.com': ['fake'],
        'libertyfederation.com': ['hate'],
        'libertymovementradio.com': ['conspiracy'],
        'libertynews.com': ['unreliable', 'bias'],
        'libertytalk.fm': ['conspiracy'],
        'libertyunyielding.com': ['bias'],
        'libertyvideos.org': ['conspiracy'],
        'libertywritersnews.com': ['clickbait', 'bias', 'unreliable'],
        'lifeandabout.com': ['bias'],
        'lifenews.com': ['bias', 'clickbait'],
        'lifeprevention.com': ['junksci'],
        'lifesitenews.com': ['clickbait', 'bias'],
        'lifezette.com': ['clickbait'],
        'lightlybraisedturnip.com': [],
        'liveactionnews.org': ['bias', 'malware', ''],
        'livefreelivenatural.com': ['warning'],
        'livevote.com': ['clickbait'],
        'lushforlife.com': ['satire'],
        'Mad­Yet.blogspot.com': [],
        'madpatriots.com': ['unreliable', 'clickbait'],
        'madworldnews.com': ['unreliable', 'clickbait', 'hate'],
        'magafeed.com': ['rumor', 'bias'],
        'makeamericagreattoday.com': ['bias', 'fake'],
        'MarketDailyNews.com': [],
        'MarketOracle.co.uk': [],
        'marshallreport.com': [],
        'MaxKeiser.com': [],
        'mediamass.net': ['fake'],
        'mediazone.news': ['rumor', 'unreliable'],
        'megafreshnews.com': ['rumor'],
        'megynkelly.us': ['fake'],
        'MemoryHoleBlog.com': [],
        'MilesFranklin.com': [],
        'militianews.com': ['conspiracy', 'bias', 'hate'],
        'MineWeb.com': [],
        'mintpressnews.com': ['political'],
        'Mises.ca': [],
        'molonlabemedia.com': [],
        'moonofalabama.org': ['bias'],
        'morningledger.com': [],
        'morningnewsusa.com': ['unreliable'],
        'mpidailymagazine.com': ['fake', 'bias'],
        'mrc.org': [],
        'mrconservative.com': ['fake', 'satire'],
        'msnbc.website': ['fake'],
        'MyBudget360.com': [],
        'mydailyrelaxation.com': [],
        'myfreshnews.com': ['fake', 'bias'],
        'myzonetoday.com': ['fake', 'bias'],
        'nahadaily.com': ['satire'],
        'nakedcapitalism.com': ['political'],
        'NarcoNews.com': [],
        'nasamoonhoax.com': [],
        'NationaLlibertyAlliance.org': [],
        'nationalreport.net': ['satire', 'fake'],
        'nationalreview.com': [],
        'NationalUFOCenter.com': [],
        'nationindistress.weebly.com': ['conspiracy'],
        'nationonenews.com': ['fake', 'conspiracy'],
        'naturalblaze.com': ['junksci', 'conspiracy'],
        'naturalnews.com': ['junksci', 'conspiracy'],
        'nbc.com.co': ['fake'],
        'nbcpolitics.org': [],
        'nbcpoll.com': [],
        'ncscooper.com': ['satire'],
        'netdania.com': [],
        'nevo.news': ['unreliable', 'bias'],
        'newcenturytimes.com': ['unreliable', 'bias'],
        'newcoldwar.org': ['political'],
        'news4ktla.com': ['fake', 'satire'],
        'newsbbc.net': ['fake'],
        'newsbiscuit.com': ['satire'],
        'newsbreakers.org': ['satire'],
        'NewsBuster.com': [],
        'newsbuzzdaily.com': ['fake'],
        'newscenterusa.com': [],
        'newscorpse.com': ['bias'],
        'newsexaminer.net': ['fake', 'satire'],
        'newsfrompolitics.com': ['fake'],
        'newslo.com': ['fake'],
        'Newsmax.com': ['unreliable', 'bias'],
        'newsmutiny.com': ['satire', 'fake'],
        'newsninja2012.com': ['bias'],
        'newsopening.com': [],
        'newstarget.com': ['conspiracy'],
        'newsthump.com': ['satire'],
        'newstoad.net': ['satire'],
        'newswatch28.com': ['fake'],
        'newswatch33.com': ['fake'],
        'newswire­24.com': ['rumor', 'unreliable'],
        'newswithviews.com': ['fake', 'conspiracy'],
        'newyorker.com/humor': ['satire'],
        'nodisinfo.com': ['conspiracy', 'unreliable'],
        'NomadCapitalist.com': [],
        'NomiPrins.com': [],
        'NoMoreFakeNews.com': ['conspiracy'],
        'nonaiswa.org/wordpress': [],
        'northcrane.com': ['unreliable'],
        'notallowedto.com': ['clickbait', 'fake'],
        'NoTime4Bull.com': [],
        'now8news.com': ['fake'],
        'nowtheendbegins.com': ['conspiracy'],
        'npiamerica.org': [],
        'NutritionalAnarchy.com': [],
        'nymeta.co': ['clickbait', 'satire'],
        'nyuzer.com': [],
        'oann.com': [],
        'oathkeepers.org': [],
        'objectiveministries.org': ['satire'],
        'observatorial.com': [],
        'observer.com': [],
        'OCCUPY.com': [],
        'occupydemocrats.com': ['clickbait', 'bias', 'unreliable'],
        'occupyliberals.com': ['bias', 'clickbait'],
        'odgossip.com': [],
        'off­guardian.org': ['bias', 'conspiracy'],
        'OffGridSurvival.com': [],
        'OfTwoMinds.com': [],
        'oftwominds.com': ['bias', 'conspiracy'],
        'oilgeopolitics.net': ['conspiracy'],
        'onlineconservativepress.com': ['fake', 'conspiracy', 'bias'],
        'opednews.com': [],
        'openmindmagazine.com': ['bias', 'conspiracy'],
        'orientalreview.org': ['bias', 'conspiracy'],
        'other98.com': ['clickbait', 'bias', 'unreliable'],
        'pakalertpress.com': ['fake'],
        'pamelageller.com': ['conspiracy', 'fake', 'bias'],
        'PandaUnite.org': [],
        'patdollar.com': ['bias', 'clickbait'],
        'patriotarchives.blogspot.com': [],
        'patriotchronicle.com': ['bias', 'clickbait'],
        'patriotnewsdaily.com': ['bias', 'satire'],
        'patriotpost.us': [],
        'patriotrising.com': ['bias', 'conspiracy'],
        'patriotupdate.com': ['bias', 'conspiracy'],
        'paulcraigroberts.org': ['bias', 'conspiracy'],
        'PeakProsperity.com': [],
        'Perpetualassets.com': [],
        'pjmedia.com': [],
        'plata.com.mx/mplata/articulos/articles.asp': [],
        'platosguns.com': ['bias', 'conspiracy', 'bias'],
        'policestateusa.com': [],
        'policyreview.info': [],
        'Politcalpiehole.com': [],
        'politicalblindspot.com': ['conspiracy', 'junkscience'],
        'politicalcult.com': ['bias', 'clickbait', 'conspiracy'],
        'politicalears.com': ['unreliable', 'clickbait'],
        'politicalo.com': ['fake'],
        'PoliticalPieHole.com': [],
        'politicalsitenews.com': ['fake'],
        'politicaltimes.org': [],
        'PoliticalTracker.com': [],
        'politicalupdator.com': ['fake', 'clickbait', 'bias'],
        'politicops.com': ['satire', 'unreliable'],
        'politicsbreaking.com': [],
        'politicsinformation.com': [],
        'politicsinfotoday.com': [],
        'politicsintheusa.com': ['unreliable', 'bias'],
        'politicsinusa.com': [],
        'politicususa.com': ['clickbait', 'unreliable'],
        'powerlineblog.com': [],
        'powerpoliticians.com': ['unreliable'],
        'pravda.ru': ['bias', 'rumor', 'conspiracy'],
        'pravdareport.com': ['bias', 'rumor', 'conspiracy'],
        'prepperwebsite.com': ['conspiracy', 'fake'],
        'presidentialvoting2016.com': ['political', 'bias', 'unreliable'],
        'press24.us': [],
        'presstv.com': ['bias', 'unreliable'],
        'presstv.ir': ['bias', 'unreliable'],
        'prisonplanet.com': ['conspiracy'],
        'prisonplanet.tv': ['conspiracy'],
        'prntly.com': ['fake'],
        'proamericanews.com': [],
        'progressivestoday.com': [],
        'projectveritas.com': ['bias', 'unreliable', 'political'],
        'proudcons.com': ['fake', 'bias'],
        'proudemocrat.com': ['political'],
        'PublicIntelligence.net': [],
        'qpolitical.com': ['bias', 'clickbait'],
        'Radio.GoldSeek.com': [],
        'randpaulreview.com': [],
        'rawforbeauty.com': ['junksci'],
        'rawstory.com': ['political', 'clickbait'],
        'rawws.com': [],
        'rbth.com': [],
        'react365.com': ['fake'],
        'readconservatives.news': ['bias', 'fake', 'clickbait'],
        'readynutrition.com': ['conspiracy'],
        'reagancoalition.com': ['bias', 'fake', 'clickbait'],
        'realfarmacy.com': ['junksci', 'conspiracy'],
        'realnewsrightnow.com': ['fake', 'satire'],
        'realplanetnews.com': ['junksci'],
        'realprogress.online': [],
        'realtimepolitics.com': ['bias', 'unreliable'],
        'redflagnews.com': ['bias', 'conspiracy', 'unreliable'],
        'RedIceCreations.com': [],
        'redstate.com': ['political', 'clickbait'],
        'redstatewatcher.com': ['bias', 'clickbait'],
        'reductress.com': ['satire'],
        'regated.com': ['bias'],
        'remedydaily.com': ['clickbait'],
        'rense.com': ['conspiracy', 'junksci'],
        'responsibletechnology.org': ['junksci'],
        'returnofkings.com': ['hate'],
        'revolutions2040.com': ['junksci', 'clickbait'],
        'rhotv.com': ['fake'],
        'RickAckerman.com': [],
        'rickwells.us': ['fake', 'conspiracy'],
        'rightalert.com': ['bias', 'unreliable'],
        'righton.com': [],
        'RightSideNews.com': [],
        'rightwingnews.com': ['bias', 'unreliable'],
        'rilenews.com': ['fake', 'satire'],
        'rinf.com': ['political'],
        'rockcitytimes.com': ['satire'],
        'ronpaulinstitute.org': ['political'],
        'rumormillnews.com': ['conspiracy', 'junksci', 'rumor'],
        'RunToGold.com': [],
        'ruptly.tv': ['political'],
        'russia­direct.org': ['political'],
        'russia­insider.com': ['bias', 'clickbait'],
        'satiratribune.com': ['satire'],
        'satirewire.com': ['satire'],
        'scrappleface.com': ['satire'],
        'SeanKerrigan.com': [],
        'secretsofthefed.com': ['conspiracy', 'junksci'],
        'sensationalisttimes.com': ['satire'],
        'sentinelblog.com': ['conspiracy', 'junksci'],
        'sgtreport.com': [],
        'shadowproof.com': [],
        'ShadowStats.com': [],
        'sheepkillers.com': ['conspiracy', 'junksci'],
        'shiftfrequency.com': [],
        'shoebat.com': ['conspiracy', 'bias'],
        'shtfplan.com': [],
        'silentmajoritypatriots.com': [],
        'Silver­Coin­Investor.com': ['conspiracy', 'bias', 'unreliable'],
        'SilverBearCafe.com': ['conspiracy'],
        'SilverDoctors.com': ['conspiracy', 'bias'],
        'SilverInvestingNews.com': [],
        'SilverSeek.com': [],
        'SilverStealers.net': ['conspiracy'],
        'SilverStrategies.com': [],
        'SJLendman.Blogspot.com': ['bias'],
        'skeptiko.com': ['conspiracy', 'junksci'],
        'smartknowledgeu.com/blog': [],
        'solari.com/blog': [],
        'sonsoflibertyradio.com': ['conspiracy', 'bias', 'unreliable'],
        'sott.net': [],
        'sourceplanet.net': [],
        'southfront.org': [],
        'southweb.org': [],
        'SovereignMan.com': [],
        'speciallifeentertainment.com': [],
        'speld.nl': [],
        'spinzon.com': [],
        'sportspickle.com': ['satire'],
        'sputniknews.com': ['bias', 'state'],
        'SRSroccoReport.com': [],
        'statenation.co': [],
        'STAWealth.com': [],
        'SteveQuayle.com': [],
        'stneotscitizen.com': ['satire'],
        'stormcloudsgathering.com': ['fake'],
        'strategic­culture.org': [],
        'stuppid.com': ['satire'],
        'subjectpolitics.com': ['fake', 'bias'],
        'suggesthealthytips.com': [],
        'superstation95.com': [],
        'supremepatriot.com': ['fake', 'bias'],
        'surenews.com': [],
        'surrealscoop.com': ['satire'],
        'SurvivalBlog.com': [],
        'SurvivalKnowHow.net': [],
        'survivopedia.com': [],
        'szandorblestman.com/index.php': [],
        'tap­news.com': [],
        'tdnewswire.com': [],
        'teapartyeconomist.com': [],
        'teapartytribune.com': [],
        'tellmenow.com': [],
        'TenthAmendmentCenter.com': [],
        'the­newspapers.com': [],
        'theamericancause.org': [],
        'theamericanindependent.wordpress.com': ['fake', 'bias'],
        'theamericanmirror.com': [],
        'theantimedia.org': [],
        'TheAuReport.com': [],
        'theautogear.com': [],
        'thebeaverton.com': ['satire'],
        'theblaze.com': ['political', 'clickbait'],
        'thebostontribune.com': ['fake'],
        'TheBRICSPost.com': [],
        'TheBrowser.com': [],
        'TheBurningPlatform.com': [],
        'thecarsmagazine.com': [],
        'thecivilian.co.nz': [],
        'thecommonsenseshow.com': ['fake', 'conspiracy'],
        'theconservativetreehouse.com': [],
        'thecontroversialfiles.net': ['fake', 'clickbait'],
        'TheCroweHouse.com': [],
        'thedailybeast.com': ['political'],
        'thedailybell.com': [],
        'TheDailyCoin.org': [],
        'TheDailyCrux.com': [],
        'thedailymash.co.uk': ['satire'],
        'thedailysheeple.com': ['conspiracy', 'bias'],
        'thedailywtf.com': ['satire'],
        'thedemocratic.site': [],
        'theduran.com': ['unreliable'],
        'theearthchild.co.za': [],
        'theeconomiccollapseblog.com': ['conspiracy', 'bias'],
        'theeventchronicle.com': ['conspiracy', 'junksci', 'clickbait'],
        'TheExtinctionProtocol.com': ['conspiracy'],
        'thefederalistpapers.org': ['bias', 'conspiracy'],
        'theforbiddenknowledge.com': ['conspiracy', 'junksci'],
        'thefreepatriot.org': ['fake', 'bias', 'clickbait'],
        'thefreethoughtproject.com': ['unreliable', 'conspiracy', 'clickbait'],
        'thegatewaypundit.com': ['bias', 'conspiracy', 'unreliable'],
        'thegoldandoilguy.com/articles': ['unreliable'],
        'thegoldwater.com': [],
        'thehardtimes.net': ['satire'],
        'theineptowl.com': ['satire'],
        'theinformedamerican.net': ['unreliable'],
        'theintercept.com': [],
        'TheInternationalForecaster.com': [],
        'TheJanssenReport.net': [],
        'thelastgreatstand.com': ['fake', 'conspiracy', 'bias'],
        'thelastlineofdefense.org': [],
        'thelibertybeacon.com': ['conspiracy', 'junksci', 'bias'],
        'thelibertymill.com': ['unreliable', 'bias', 'conspiracy'],
        'themadisonmisnomer.com': ['satire'],
        'themideastbeast.com': [],
        'themindunleashed.com': ['conspiracy', 'junksci', 'clickbait'],
        'themindunleashed.org': ['conspiracy', 'junksci', 'clickbait'],
        'TheMogamboGuru.com': [],
        'themuslimissue.wordpress.com': ['hate', 'conspiracy'],
        'themznews.info': [],
        'thenewamerican.com': [],
        'thenewinquiry.com': [],
        'thenewsdoctors.com': [],
        'TheNewsFile.com': [],
        'thenewsnerd.com': ['satire'],
        'theonion.com': ['satire'],
        'theopenscroll.blogspot.com': [],
        'theorganicprepper.ca': [],
        'TheOutsiderClub.com': [],
        'theoxymoron.co.uk': [],
        'thepeoplescube.com': [],
        'ThePeoplesVoice.net': [],
        'thephaser.com': ['conspiracy'],
        'thepoke.co.uk': ['satire'],
        'thepoliticalinsider.com': ['conspiracy', 'bias', 'unreliable'],
        'thepostemail.com': [],
        'theracketreport.com': ['fake', 'satire'],
        'therealstrategy.com': ['bias', 'conspiracy', 'hate'],
        'therebel.media': [],
        'thereporterz.com': ['fake'],
        'therightists.com': ['fake', 'bias'],
        'therightplanet.com': [],
        'therightstuff.biz': ['hate'],
        'therundownlive.com': [],
        'therussophile.org': [],
        'thesaker.is': [],
        'theshovel.com.au': ['satire'],
        'theskunk.org': ['satire'],
        'thesleuthjournal.com': [],
        'thespoof.com': ['satire'],
        'thestatelyharold.com': ['satire'],
        'thetimesoftheworld.com': ['satire'],
        'thetruthaboutcancer.com': [],
        'thetruthdivision.com': ['fake', 'bias'],
        'thetruthseeker.co.uk': ['fake', 'conspiracy', 'junksci'],
        'TheTruthWins.com': [],
        'theunrealtimes.com': ['satire'],
        'theuspatriot.com': ['satire', 'fake'],
        'thevalleyreport.com': ['satire'],
        'TheVictoryReport.org': [],
        'thewatchtowers.com': ['bias', 'conspiracy', 'clickbait'],
        'TheWealthWatchman.com': [],
        'theworldstyle.com': [],
        'thirdworldtraveler.com': [],
        'thisismynewworld.com': [],
        'threepercenternation.com': ['fake', 'conspiracy', 'bias'],
        'thrivemovement.com': [],
        'TomWoods.com': [],
        'topekasnews.com': ['satire'],
        'topinfopost.com': ['clickbait', 'unreliable', 'conspiracy'],
        'topnewspolitics.com': [],
        'topratedviral.com': [],
        'toprightnews.com': [],
        'totalworldnews.com': [],
        'traderdan.com': [],
        'tradewithdave.com': [],
        'TragedyandHope.com': [],
        'trendingnewsguide.com': [],
        'trendingnewstoday.net': [],
        'tribuneherald.net': [],
        'tribunist.com': [],
        'TrueActivist.com': ['clickbait', 'unreliable'],
        'trueeconomics.blogspot.com': [],
        'truepundit.com': ['bias', 'clickbait'],
        'trumpvision365.com': ['fake'],
        'trunews.com': [],
        'truthandaction.org': ['bias', 'conspiracy', 'clickbait'],
        'truthbroadcastnetwork.com': ['conspiracy', 'clickbait'],
        'truthfeed.com': ['hate', 'bias', 'conspiracy'],
        'truthfrequencyradio.com': ['conspiracy'],
        'truthingold.com': [],
        'TruthInMedia.com': [],
        'truthkings.com': ['bias', 'conspiracy', 'junksci'],
        'truthnetwork.com': [],
        'truthrevolt.org': ['bias', 'hate'],
        'TruthStreamMedia.com': [],
        'ttmygh.com/blog': [],
        'tunerspeed.com': [],
        'turnerradionetwork.com': [],
        'twitchy.com': ['clickbait', 'rumor'],
        'tyronetribulations.com': [],
        'ufoholic.com': ['conspiracy'],
        'unclesamsmisguidedchildren.com': ['bias'],
        'unconfirmedsources.com': ['satire'],
        'undergroundhealth.com': [],
        'undergroundworldnews.com': ['fake', 'conspiracy', 'bias'],
        'unionleader.com': [],
        'unitedmediapublishing.com': ['fake'],
        'universepolitics.com': [],
        'unz.com': [],
        'us.blastingnews.com': ['satire', 'unreliable'],
        'usa2016elections.com': [],
        'usacoinbook.com': [],
        'usadailypolitics.com': ['fake'],
        'usadailytime.com': [],
        'usahitman.com': ['fake', 'conspiracy'],
        'usainfobox.com': [],
        'usajournalist.com': [],
        'usalinepolitics.com': [],
        'usalinepoliticsnow.com': [],
        'usamagazinestudio.com': [],
        'usanews24hrs.com': [],
        'usanewsflash.com': ['fake', 'bias', 'clickbait'],
        'usanewshome.com': [],
        'usanewsinsider.com': ['fake', 'bias', 'clickbait'],
        'usanewspolitics.com': [],
        'usanewsstudio.com': [],
        'usaonlinepolitics.com': [],
        'usaonlinetoday.com': [],
        'usaphase.com': [],
        'usapoliticsdaily.com': [],
        'usapoliticsnow.com': [],
        'usapoliticstoday.com': ['bias', 'unreliable'],
        'usapoliticus.com': [],
        'usapowernews.com': [],
        'usascan.com': [],
        'usasupreme.com': ['fake'],
        'usatwentyfour.com': [],
        'USAWatchdog.com': [],
        'uschronicle.com': ['bias', 'conspiracy', 'hate'],
        'usconservativetoday.com': ['fake'],
        'usdcrisis.com': [],
        'usdefensewatch.com': ['unreliable'],
        'usfanzone.com': [],
        'ushealthyadvisor.com': ['fake', 'conspiracy', 'junksci'],
        'usherald.com': ['bias', 'conspiracy', 'unreliable'],
        'uslifetoday.com': [],
        'usmediacenter.com': [],
        'uspolitics24.com': [],
        'uspoliticslive.com': ['fake', 'bias', 'conspiracy'],
        'usslibertyveterans.org': [],
        'UsualSuspect.net': [],
        'usuncut.com': ['clickbait', 'bias', 'unreliable'],
        'usviewer.com': [],
        'utopiathecollapse.com': [],
        'vdare.com': [],
        'veteransnewsnow.com': [],
        'veteranstoday.com': ['bias', 'unreliable'],
        'vigilantcitizen.com': ['fake', 'conspiracy'],
        'viralliberty.com': ['fake', 'bias', 'clickbait'],
        'viraltube.nl': [],
        'voltairenet.org': [],
        'vonpress.com': [],
        'votocrat.com': [],
        'wakeupthesheep.com': [],
        'wakingtimes.com': [],
        'wakingupwisconsin.com': ['conspiracy'],
        'wallstreetexaminer.com': [],
        'WallStreetOnParade.com': [],
        'washingtonexaminer.com': ['unreliable', 'bias', 'conspiracy'],
        'washingtonsblog.com': ['bias', 'conspiracy', 'satire'],
        'waterfordwhispersnews.com': ['satire'],
        'wb7.hk': [],
        'wealthcycles.com': [],
        'wealthwire.com': [],
        'wearechange.org': ['bias', 'conspiracy'],
        'weaselzippers.us': [],
        'webdaily.com': ['fake', 'conspiracy', 'bias'],
        'weeklystandard.com': [],
        'weeklyworldnews.com': ['fake', 'rumor', 'clickbait'],
        'weshapelife.org': [],
        'westernjournalism.com': ['bias', 'clickbait'],
        'whatdoesitmean.com': ['conspiracy'],
        'whatreallyhappened.com': ['conspiracy', 'rumor'],
        'whitepower.com': ['hate', 'conspiracy', 'bias'],
        'whowhatwhy.com': ['unreliable'],
        'whowhatwhy.org': [],
        'whydontyoutrythis.com': ['junksci', 'rumor'],
        'WideAwakeNews.com': [],
        'wikileaks.com': [],
        'wikileaks.org': [],
        'wikispooks.com': [],
        'WilliamBanzai7.blogspot.com': [],
        'Willyloman.wordpress.com': ['conspiracy'],
        'winkprogress.com': ['satire'],
        'winningdemocrats.com': ['bias', 'unreliable'],
        'witscience.org': ['satire'],
        'wnd.com': ['bias', 'clickbait', 'unreliable'],
        'WolfStreet.com': [],
        'wonkie.com': ['satire'],
        'world24monitor.com': [],
        'worldcallyoutoday.com': [],
        'worlddaily.info': [],
        'worldnewsdailyreport.com': ['satire'],
        'worldnewspolitics.com': ['bias'],
        'worldpoliticsus.com': ['fake'],
        'worldrumor.com': ['fake'],
        'worldstoriestoday.com': ['fake'],
        'worldtruth.tv': ['conspiracy', 'junksci'],
        'worldwidehealthy.com': ['junksci', 'clickbait'],
        'wundergroundmusic.com': ['satire'],
        'www.rt.com': ['state'],
        'X22Report.com': [],
        'yellowhammernews.com': ['political'],
        'yesimright.com': ['fake', 'bias'],
        'Youngcons.com': ['bias', 'unreliable'],
        'yourfunpage.com': ['fake'],
        'yournationnews.com': [],
        'YourNewsline.wordpress.com': [],
        'yournewswire.com': ['clickbait', 'junksci'],
        'zaytung.com': [],
        'Zengardner.com': [],
        'zerohedge.com': ['conspiracy'],
        'zootfeed.com': ['conspiracy'],
    }
)
